# EXPLORATORY DATA ANALYSIS EDA

![EDA.png](./img/steps_EDA.png)

# Proyecto módulo Data Analysis
En este proyecto vas a aplicar todo lo aprendido en el Fundamentals y el módulo de Data Analysis del bootcamp. Tendrás que realizar un análisis exploratorio de datos y presentar los resultados. Ten en cuenta lo siguiente:

* **Miembros**: El proyecto es individual
* **Datos**: Tienes que conseguir los datos por tu cuenta (ver abajo)
* **Fecha límite**: Viernes 4 de Abril a las 9.00h a través del campus y ese mismo día son las presentaciones. Tendremos dos entregas previas (Viernes 28 de Marzo a las 9.00h con un punto de partida de tema, hipótesis y datasets. El Jueves 3 de Abril a las 9.00h con el repositorio de github).


## Objetivo
Lo que queremos mediante este tipo de análisis es resolver un problema real apoyándonos en datos, por lo que tendrás que plantearte primero qué es lo que quieres resolver, y a partir de ahí identificar fuentes de datos e ir trabajando con ellos para acabar llegando a una conclusión. Plantea tus hipótesis antes de realizar el análisis exploratorio y después verifica si se han cumplido, o si has descubierto mediante los datos que lo que ocurría era justamente lo opuesto a lo que pensabas.


## Evaluación
* **Presentación** máximo 10 minutos donde expondrás tu caso (ver apartado Presentación)
* **Memoria** un jupyter notebook donde explicarás el desarrollo del proyecto con markdown y código de python. (Introducción, Fuentes de datos, Limpiezas, Desarrollo análisis, Medidas estadísticas, Visualizaciones, Conclusiones,..)
* **Código** hay que entregar todo el código desarrollado. También se tiene en cuenta (tipo solución, documentación...)
* **Subir el proyecto a tu GitHub personal**. Este gran esfuerzo tiene que ser compartido, y te recomiendo que te crees un repositorio en GitHub para ir añadiendo tus proyectos personales. En caso de que el proyecto se componga de datos sensibles o no se quiera publicar, se puede mantener en repositorio privado (consultar profesores).


## Entregable
El enlace al repositorio de github que habrá que subir a Google Classroom. Debe constar:
* Presentación
* Memoria
* Código

El codigo deberá seguir la siguiente estructura de carpetas:
1. src/: aquí irá todo el código
2. src/data: todos los archivos de datos utilizados en el analisis. No subir a GitHub archivos demasiado pesados.
3. src/notebooks: los notebooks usados para pruebas.
4. src/utils: todos los modulos, funciones auxiliares o clases creados para el desarrollo del proyecto.
5. src/memoria.ipynb: en este notebook tendrás que resumir de forma clara y ordenada todos los pasos de la analítica.

**GitHub**: hay que crear un README con una descripción de tu proyecto. Breve. El objetivo de este README es enterarse de forma rápida de qué va tu proyecto y qué tecnologías has utilizado para llevarlo a cabo, no es más que un escaparate de tu trabajo. Hay que ir documentando bien los trabajos para acabar el bootcamp con un buen portfolio. En [este enlace](https://github.com/alexhuang1117/Data-Science-Portfolio) tienes un ejemplo de cómo tener documentados los proyectos en tu GitHub. Encontrarás en el notebook de markdown todo lo que necesitas para crear un README decente.

## Presentación
Puesto que en la vida real la mayoría de presentaciones se realizan a un público no técnico, ésta no va a ser menos. Si tienes que explicar algo técnico, cuéntalo, pero para alguien que no sabe lo que significa. Por ejemplo, ¿cómo contarías qué es una matriz de correlación? **No queremos ver código**, ni cómo estructuraste el proyecto en carpetas, ni cómo de difícil ha sido limpiarlo. Al cliente/tu jefe le da igual :). Explicar cosas técnicas lleva tiempo por lo que piensa muy bien en lo que vas a decir y en cómo lo sintetizarás.

Tendrás que exponer bien tu caso de uso con su contexto, explicar qué transformaciones y línea de análisis has abordado, y acabar la presentación con unas conclusiones y oportunidades que nos brinda el proyecto, para cerrar el plantemiento inicial del caso de uso. 

**¿Formatos de la presentación?** Nada de Notebooks. Formato presentación en PowerPoint, Google Slides, Prezi o la plataforma que mejor conozcas, siendo perfectamente combinable con un dashboard.

**Consejos**: Si usas un PowerPoint... será tu apoyo a la hora de presentar, aquí el protagonista es tu discurso. Por favor, que la presentación no sea un conjunto de puntos inconexos. Intenta llevar un hilo, como si de una historia se tratase. Véndete, destaca las fortalezas de tu trabajo sobre las debilidades. Interactúa con el público. Si vas a contar algo de negocio, ¿puedes traducirlo a números? ¿Qué impacto tendrá tu analítica?. Muestra algunos datos concretos (estadísticos simples) para justificar tu business case o para cerrar tu presentación. Si has elegido una temática que está acorde con tus gustos/background, aprovecha al principio para contarlo y empatizar mucho más con el público. Si vas a hacer una demo, grábala por si te falla algo en la presentación (conexión a Internet). Prepárate las respuestas a algunas posibles preguntas en un anexo de la presentación.

**NOTA**: existen muchas plantillas gratuitas en la web para hacer presentaciones. [Aquí tienes unas cuantas](https://www.free-powerpoint-templates-design.com/free-powerpoint-templates-design/).


## Pasos del proyecto

1. Elegir temática
    1. **Elegir una temática y buscar datos en función de la misma**. Puede ocurrir que no encuentres datos que te sirvan para tu propósito, o que tengas que conseguirlos mediante APIs, scrapping, descarga de BBDD.... No obstante, esta opción es la que más se asemejaría a un caso real, ya que una gran problemática en este tipo de proyectos es encontrar datos.

    2. **Directamente ir a páginas de datos abiertos y escoger un dataset de tu interés**. Si no tienes clara la temática puedes buscar en alguno de los enlaces de datos (recomendable Kaggle) y escoger un tema que te motive.

2. Obtención de datos. ¿Puedes llevar a cabo el proyecto con estos datos?
3. Define tu hipótesis. ¿Qué piensas que puedes analizar de estos datos? ¿Qué vas a poder resolver? ¿Cómo lo vas a llevar a cabo? (**Viernes 20 de Diciembre**). Podrás utilizar el periodo de navidades para terminar de validarlo y pivotar a otro tema.
4. Preprocesado: obtén todos los datos de las diferentes fuentes que hayas utilizado, juntalos y ponlos en un formato entendible.
5. Limpia los datos: transformaciones, duplicados, missings, columnas inútiles...
6. Exploratorio: obtén todos los estadísticos y gráficos que necesites para entender bien tu dataset y apoyar tus argumentos.
7. Concluye con tu análisis si estabas o no en lo cierto acerca de tu planteamiento y tu hipótesis.
8. Crea un dashboard para representar tu análisis exploratorio si lo consideras necesario.
9. Crea una presentación con un hilo conductor sobre tu análisis exploratorio
10. Documenta tu proyecto y súbelo a GitHub.


## Datos
¿De dónde saco los datos? Posibles fuentes:
- [Web de datos abiertos del gobierno](https://datos.gob.es/)
- [OpenStreetMap](https://wiki.openstreetmap.org/wiki/API). Datos de ubicaciones (como Google Maps) abiertos
- [Obtención de datos bursátiles](https://financetrain.com/best-python-librariespackages-finance-financial-data-scientists/)
- [ESRI Datos abiertos España](https://opendata.esri.es/)
- [INE](https://www.ine.es/nomen2/ficheros.do)
- [Red.es](https://www.red.es/redes/es/que-hacemos/datos-abiertos)
- [Datos abiertos gobierno](https://www.hacienda.gob.es/es-ES/GobiernoAbierto/Datos%20Abiertos/Paginas/Catalogodedatosabiertos.aspx)
- [Ayuntamiento de Madrid](https://datos.madrid.es/portal/site/egob/)
- [Ayuntamiento de Barcelona](https://opendata-ajuntament.barcelona.cat/es)
- [Metro de Madrid](https://data-crtm.opendata.arcgis.com/)
- [Portal datos europeo I](https://data.europa.eu/euodp/es/home)
- [Portal datos europeo II](https://www.europeandataportal.eu/data/datasets?locale=en&minScoring=0)
- [Google Dataset Search](https://datasetsearch.research.google.com/)
- [Indicadores macro mundiales](https://databank.worldbank.org/home)
- [Indicadores macro mundiales](https://ilostat.ilo.org/data/country-profiles/)
- [Amplio repositorio de Datasets](https://datacommons.org/)
- [Datos macro mundiales](https://www.gapminder.org/data/)
- [GitHub con gran cantidad de APIs públicas](https://github.com/public-apis/public-apis)
- [Datos sobre migraciónn](https://migrationdataportal.org/es/node/2955)
- [Web de datos abiertos de España](https://www.epdata.es/)
- [Redapi: Plataforma de APIs con amplia capa gratuita](https://rapidapi.com/blog/most-popular-api/)
- [Artículo para trabajar con histórico de bolsa](https://towardsdatascience.com/how-to-get-stock-data-using-python-c0de1df17e75)
- [Otro gran repo de datasets](https://www.paperswithcode.com/datasets)
- [API de Idealista](https://www.idealista.com/data/productos/desarrollo/api-de-testigos)
- [API de Booking](https://developers.booking.com/api/index.html)
- [API de Tripadvisor](http://developer-tripadvisor.com/content-api/)
- [API de Facebook](https://developers.facebook.com/docs/apis-and-sdks?locale=es_ES)
- [API de Twitter](https://developer.twitter.com/en/docs)
- [API de Instagram](https://www.instagram.com/developer/)
- [APIs de Google Maps](https://cloud.google.com/maps-platform?hl=es)
- [Google Timeline](https://www.google.es/maps/timeline?pb). Todo tu registro de actividad de Google, como los lugares que has visitado

- [Alexa. Tráfico de webs](https://www.alexa.com/siteinfo)
- [Catastro](https://ovc.catastro.meh.es/ovcservweb/OVCSWLocalizacionRC/OVCCoordenadas.asmx)
- [Airbnb](http://insideairbnb.com/index.html)
- Web scrapping. Acceso automatizado a cualquier web.
- Kaggle: página con competiciones de data scientists. Muchísimos datasets.
- QPython 3L: APP para ejecutar código Python en el movil. Podrás sacar datos de tu actividad con el teléfono (horarios, geoposicionamiento)
- Coronavirus. Se están empezando a librerar muchísimos datasets con datos del coronavirus en todo el mundo. En Kaggle hay varios.



Si tienes algún tema sobre el que quieras investigar, y no encaja con ninguno de los enlaces propuestos, consúltalo con los profesores para investigar de dónde podríamos sacar datos para ese análisis.

In [69]:
import numpy as np
import pandas as pd

<h1>Data importaciones UREA a Ecuador 2009-2024</h1>

En la casilla siguiente me bajare la data de las importaciones de Urea a Ecuador del 2009 al 2024

In [70]:
data1 = pd.read_csv("/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data /Importaciones UREA/01:01:2009 - 31:12:2011.csv") 
data2 = pd.read_csv("/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data /Importaciones UREA/01:12:2012-31:12:2014.csv") 
data3 = pd.read_csv("/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data /Importaciones UREA/01:01:2015-31:12:2015.csv") 
data4 = pd.read_csv("/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data /Importaciones UREA/01:01:2016-31:12:2018.csv") 
data5 = pd.read_csv("/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data /Importaciones UREA/01:01:2019-31:12:2019.csv") 
data6 = pd.read_csv("/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data /Importaciones UREA/01:01:2020-31:12:2022.csv") 
data7 = pd.read_csv("/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data /Importaciones UREA/01:01:2023-31:12:2023.csv") 
data8 = pd.read_csv("/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data /Importaciones UREA/01:01:2024-12:31:2024.csv")

Ahora concatenare todos estos datos en orden descendente

In [73]:
data_total_raw_importaciones_urea = pd.concat([data1, data2, data3, data4, data5, data6, data7, data8], 
                       axis=0,           
                       ignore_index=True)

In [74]:
data_total_raw_importaciones_urea.to_csv('Data_2/data_total_raw_importaciones_urea.csv')

Con esta funcion puedo visualizar todas las columnas

In [75]:
pd.options.display.max_columns = None
data_total_raw_importaciones_urea

,RAZON SOCIAL,POTENCIAL UNO,NOMBRE COMERCIAL,RUC,CONSIGNATARIO,POSICION ARANCELARIA,CODIGO COMPLEMENTARIO,CODIGO SUPLEMENTARIO,DESCRIPCION POSICION,DESCRIPCION DEL DESPACHO,MARCA,MODELO,REFRENDO,ITEM,DAU,FECHA DESPACHO,FECHA EMBARQUE,FECHA LLEGADA,FECHA LIQUIDACION,FECHA PAGO,FECHA SALIDA ALMACEN,REGIMEN,NUMERO MANIFIESTO,MANIFIESTO,CODIGO DOCUMENTO TRANSPORTE,DOCUMENTO TRANSPORTE,ADUANA,PAIS ORIGEN,PAIS PROCEDENCIA,PAIS EMBARQUE,PUERTO EMBARQUE,VIA TRANSPORTE,CONTENEDORES,DEPOSITO,FOB U$S,FLETE U$S,SEGURO U$S,CIF U$S,FACTURA,VALOR FACTURA U$S,BASE IMPONIBLE U$S,KGS NETO,KGS BRUTO,UNIDADES,TIPO UNIDAD,PRECIO UNITARIO U$S,CANTIDAD COMERCIAL,UNIDAD COMERCIAL,PRECIO UNITARIO COMERCIAL U$S,TIPO UNIDAD NOMENCLADOR,ADVAL,MONEDA,EMBARCADOR,INCOTERM,CODIGO LIBERACION,ESTADO MERCADERIA,CLASE MERCADERIA,PAIS DESTINO,TOTAL FOB U$S,TOTAL FLETE U$S,TOTAL SEGURO U$S,TOTAL CIF U$S,TOTAL KGS NETO,TOTAL KGS BRUTO,TOTAL BASE IMPONIBLE,TOTAL CANTIDAD BULTOS,TOTAL AJUSTES,TOTAL OTROS AJUSTES,CLASE,VERIFICADOR,AGENTE AFIANZADO,NAVE,AGENCIA TRANSPORTE,EMPRESA TRANSPORTE,AFORADOR,FECHA AFORO,TIPO AFORO,ACTIVIDAD PRINCIPAL DEL IMPORTADOR,DIRECCION DEL IMPORTADOR,DIRECCION DEL CONSIGNATARIO,CONSOLIDADORA
0,DELCORP S.A.,SERVICIOS AGRICOLAS SOCIEDAD ANONIMA COMERCIAL...,DELCORP S.A.,991265414001,NaN,3102.10.10.00,0,0,Con un porcentaje de nitrógeno superior o igua...,"UREA-COLOR BLANCO, NITROGENO 46.0% MIN GRANULO...",NaN,NaN,28200910000815,1,14279592.0,2009-01-06,2008-10-27,2008-12-13,0000-00-00,0000-00-00,0000-00-00,IMPORTACION A CONSUMO,NaN,1851,NaN,MSCUVN989404,GUAYAQUIL MARITIMO,CHINA,VIET NAM,VIET NAM,VNSGN-HO CHI MINH CITY,MARITIMO,0.0,NaN,"359,550.25","76,110.00","1,157.71","436,817.97",NaN,0.0,0.0,"575,000.00","576,725.00","575,000.00",NaN,0.63,0.0,NaN,0.0,"kg, Kilogramo",0.0,DOL,KEYTRADE,NaN,"IVA 0 semillas ,bulbos,plantas,esquejes,raices...",NUEVO,NaN,NO ESPECIFICADO,"359,550.25","76,110.00","1,157.71","436,817.97","575,000.00","576,725.00",0.0,"11,500.00",0.0,0.0,BOLSA,ADUANA,01902288: ILLINGWORTH GARCIA CRISTOBAL LUIS,MSC PARANA,MEDITERRANEAN SHIPPING CO.ECUADOR C.A.,MEDITERANEAN SHIPPING,NaN,0000-00-00,AFORO FISICO,VENTA AL POR MAYOR DE FERTILIZANTES,V.E. ESTRADA 114 Y BALSAMOS,NaN,NaN
1,DUPOCSA PROTECTORES QUIMICOS PARA EL CAMPO S. A.,SERVICIOS AGRICOLAS SOCIEDAD ANONIMA COMERCIAL...,NaN,990856583001,NaN,3102.10.10.00,0,0,Con un porcentaje de nitrógeno superior o igua...,UREA,NaN,NaN,82200910000803,1,14581329.0,2009-02-19,2009-02-18,2009-02-20,0000-00-00,0000-00-00,0000-00-00,IMPORTACION A CONSUMO,NaN,810,NaN,PE-0192-04-2009020,HUAQUILLAS,RUSSIAN FEDERATION,PERU,PERU,PEPAI-PAITA,CARRETERA,0.0,NaN,"75,664.81","6,800.00",241.26,"82,706.07",NaN,0.0,0.0,"240,000.00","240,400.00",240.00,NaN,315.27,0.0,NaN,0.0,"kg, Kilogramo",0.0,DOL,ADM ANDINA PERU SRL,NaN,"IVA 0 semillas ,bulbos,plantas,esquejes,raices...",NUEVO,NaN,NO ESPECIFICADO,"75,664.81","6,800.00",241.26,"82,706.07","240,000.00","240,400.00",0.0,"4,800.00",0.0,0.0,SACO DE TEJIDO PLASTICO,ADUANA,01903692: PRIETO VEGA LAURA MACLOVIA,NaN,SERVIMODAL S.A.C.,SERVIMODAL S.A.C.,NaN,0000-00-00,AFORO DOCUMENTAL,5190-VENTA AL POR MAYOR DE OTROS PRODUCTOS,"PARA EL CAMPO VIA DURAN - TAMBO KM 9, DURAN",NaN,NaN
2,BANCO NACIONAL DE FOMENTO BNF,SERVICIOS AGRICOLAS SOCIEDAD ANONIMA COMERCIAL...,NaN,1760002790001,NaN,3102.10.10.00,0,0,Con un porcentaje de nitrógeno superior o igua...,UREA GRANULAR,NaN,NaN,28200910018185,1,14623238.0,2009-03-06,2009-03-02,2009-03-10,0000-00-00,0000-00-00,0000-00-00,IMPORTACION A CONSUMO,NaN,467,NaN,1,GUAYAQUIL MARITIMO,VENEZUELA,VENEZUELA,VENEZUELA,ZZZZZ-PUERTO DESCONOCIDO,MARITIMO,0.0,NaN,"5,781,583.00","748,095.50","17,682.18","6,547,360.50",NaN,0.0,0.0,"20,648,510.00","20,648,510.00","20,648.51",NaN,280.00,0.0,NaN,0.0,"kg, Kilogramo",0.0,DOL,IPSL INTERNATIONAL P,NaN,"Tarifa 0 IVA, Sector público, cuando concurran...",NUEVO,NaN,NO ESPECIFICADO,"5,781,583.00","748,095.50","17,682.18","6,547,360.50","20,648,510.00","20,648,510.00",0.0,1.00,0.0,0.0,SIN ENVASAR O SIN EMPAQUETAR,ADUANA,01903476: PAREDES VINUEZA SEGUNDO BENJAMIN,NaN,INVESTAMAR S.A.,AGENCIA NO REGULAR,NaN,0000-00-00,AFORO DOCUMENTAL,NaN,107 ANTE Y AV 10 DE AGOSTO,NaN,NaN
3,DUPOCSA PROTECTORES QUIMICOS PARA EL CAMPO S. A.,SERVICIOS AGRICOLAS SOCIEDAD ANONIMA COMERCIAL...,NaN,990856583001,NaN,3102.10.10.00,0,0,Con un porcentaje de nitrógeno superior o igua...,UREA PERLADA PARA USO FERTILIZANTE,NaN,NaN,82200910001064,1,14624789.0,2009-03-06,2009-03-04,2009-03-09,0000-00-00,0000-00-00,0000-00-00,IMPORTACION A CONSUMO,NaN,1118,NaN,028-2009,HUAQUILLAS,PERU,PERU,PERU,PEPAI-PAITA,CARRETERA,0.0,NaN,"76,244.80","4,800.00",243.45,"81,288.25",NaN,0.0,0.0,"240,000.00","240,400.00","240,000.00",NaN,0.32,0.0,NaN,0.0,"kg, Kilogramo",0.0,DOL,ADM ANDINA PERU S.R.,NaN,"IVA 0 semillas ,bulbos,plantas,esquejes,raices...",NUEVO,NaN,NO ESPECIFICADO,"76,244.80","4,800.00",243.45,"81,288.25","240,000.00","240,400.00",0.0,"4,800.00",0.0,0.0,SACO,ADUANA,01906284: NAVARRO RAMON ALBERTO DANILO,NaN,SANTA ESPERANZA S.R.L.,SANTA ESPERANZA S.R.L.,NaN,0000-00-00,AFORO DOCUMENTAL,5190-VENTA AL POR MAYOR DE OTROS PRODUCTOS,"PARA EL CAMPO VIA DURAN - TAMBO KM 9, DURAN",NaN,NaN
4,DUPOCSA PROTECTORES QUIMICOS PARA EL CAMPO S. A.,SERVICIOS AGRICOLAS SOCIEDAD ANONIMA COMERCIAL...,NaN,990856583001,NaN,3102.10.10.00,0,0,Con un porcentaje de nitrógeno superior o igua...,UREA PERLADA,NaN,NaN,82200910001123,1,14633955.0,2009-03-11,2009-03-10,2009-03-11,0000-00-00,0000-00-00,0000-00-00,IMPORTACION A CONSUMO,NaN,1197,NaN,PE0192042009033,HUAQUILLAS,RUSSIAN FEDERATION,PERU,PERU,PEPAI-PAITA,CARRETERA,0.0,NaN,"76,144.81","6,400.00",243.45,"82,788.26",NaN,0.0,0.0,"240,000.00","240,400.00","240,000.00",NaN,0.32,0.0,NaN,0.0,"kg, Kilogramo",0.0,DOL,ADM ANDINA PERU SRL,NaN,"IVA 0 semillas ,bulbos,plantas,esquejes,raices...",NUEVO,NaN,NO ESPECIFICADO,"76,144.81","6,400.00",243.45,"82,788.26","240,000.00","240,400.00",0.0,"4,800.00",0.0,0.0,SACO DE TEJIDO PLASTICO,ADUANA,01903692: PRIETO VEGA LAURA MACLOVIA,NaN,SERVIMODAL S.A.C.,SERVIMODAL S.A.C.,NaN,0000-00-00,AFORO DOCUMENTAL,5190-VENTA AL POR MAYOR DE OTROS PRODUCTOS,"PARA EL CAMPO VIA DURAN - TAMBO KM 9, DURAN",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1982,PRECISAGRO S.A.,NaN,NaN,1792522005001,NaN,3102.10.10.00,0,1,Con un porcentaje de nitrógeno superior o igua...,"UREA, UREA",SIN MARCA,SIN MODELO,2820241002997434,1,NaN,2024-12-16,2024-12-02,2024-12-23,2024-12-16,2024-12-17,0000-00-00,IMPORTACION A CONSUMO,NaN,CEC202477870199,CEC20247787019900020000,EC-01,GUAYAQUIL MARITIMO,TRINIDAD AND TOBAGO,TRINIDAD AND TOBAGO,TRINIDAD AND TOBAGO,TTPTS-POINT LISAS,MARITIMO,0.0,NaN,"1,062,900.00",0.0,"10,629.00","1,073,529.00",FG1-01097,"1,076,809.12","1,208,229.00","3,000,000.00",0.0,"3,000,000.00",KILOGRAMO BRUTO,0.35,"3,000.00",TM,354.3,"kg, Kilogramo",0.0,DOL,INCOFE S.A.S.,CIF,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,"1,076,809.12",0.0,"10,629.01","1,087,438.12","3,039,258.00",0.0,"1,222,138.12",0.0,0.0,0.0,NaN,NaN,01902441: TORRES & TORRES AGENTES DE ADUANAS T...,SEAHORSE,02777787-REMAR REPRESENTACIONES MARITIMAS DEL ...,02777787-REMAR REPRESENTACIONES MARITIMAS DEL ...,GEFARIAS-FARIAS VARGAS GENESIS ANDREINA,0000-00-00,AFORO DOCUMENTAL,9993-OTROS,"Sector Quitumbe, calle S31 y Quipu, conjunto A...",NaN,NaN
1983,PRECISAGRO S.A.,NaN,NaN,1792522005001,NaN,3102.10.10.00,0,1,Con un porcentaje de nitrógeno superior o igua...,"UREA, UREA",SIN MARCA,SIN MODELO,2820241002997434,2,NaN,2024-12-16,2024-12-02,2024-12-23,2024-12-16,2024-12-17,0000-00-00,IMPORTACION A CONSUMO,NaN,CEC202477870199,CEC20247787019900020000,EC-01,GUAYAQUIL MARITIMO,TRINIDAD AND TOBAGO,TRINIDAD AND TOBAGO,TRINIDAD AND TOBAGO,TTPTS-POINT LISAS,MARITIMO,0.0,NaN,"13,909.11",0.0,0.01,"13,909.12",FG1-01097,"1,076,809.12","13,909.14","39,258.00",0.0,"39,258.00",KILOGRAMO BRUTO,0.35,39.26,TM,354.3,"kg, Kilogramo",0.0,DOL,INCOFE S.A.S.,CIF,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01902441: TORRES & TORRES AGENTES DE ADUANAS T...,SEAHORSE,02777787-REMAR REPRESENTACIONES MARITIMAS DEL ...,02777787-REMAR REPRESENTACIONES MARITIMAS DEL ...,GEFARIAS-FARIAS VARGAS GENESIS ANDREINA,0000-00-00,AFORO DOCUMENTAL,9993-OTROS,"Sector Quitumbe, calle S31 y Quipu, conjunto A...",NaN,NaN
1984,YARECUADOR CIA LTDA,NaN,NaN,1792028140001,YARECUADOR CIA. LTDA.,3102.10.10.00,0,1,Con un porcentaje de nitrógeno superior o igua...,"UREA GRANULAR, UREA GRANULAR",SIN MARCA,PA38M2000,2820241003034107,1,NaN,2024-12-19,2024-12-02,2024-12-23,2024-12-19,2024-12-19,0000-00-00,IMPORTACION A CONSUMO,NaN,CEC202477870199,CEC20247787019900010000,1,GUAYAQUIL MARITIMO,TRINIDAD AND TOBAGO,TRINIDAD AND TOBAGO,TRINIDAD AND TOBAGO,TTPTS-POINT LISAS,MARITIMO,0.0,NaN,"780,340.00",0.0,"7,803.40","788,143.38",STL0110110448,"790,551.44","885,229.38","2,200,000.00",0.0,"2,200,000.00",KILOGRAMO BRUTO,0.35,"2,200.00",TM,354.7,"kg, Kilogramo",0.0,DOL,YARA SWITZERLAND LTD,CIF,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,"790,551.44",0.0,"7,905.51","798,456.94","2,228,789.00",0.0,"895,542.94",0.0,0.0,0.0,NaN,NaN,01902441: TORRES & TORRES AGENTES DE ADUANAS T...,SEAHORSE,02777787-REMAR REPRESENTACIONES MARITIMAS DEL ...,02777787-REMAR REPRESENTACIONES MARITIMAS DEL ...,NaN,0000-00-00,AFORO AUTOMATICO,0140-ACTIVIDADES DE SERVICIOS AGRICOLAS Y GANA...,KM 1 5 SOLAR 120 Y LOS ARCOS EDIF LOS A,NaN,NaN
1985,YARECUADOR CIA LTDA,NaN,NaN,1792028140001,YARECUADOR CIA. LTDA.,3102.10.10.00,0,1,Con un porcentaje de nitrógeno superior o igua...,"UREA GRANULAR, UREA GRANULAR",SIN MARCA,PA38M2000,2820241003034107,2,NaN,2024-12-19,2024-12-02,2024-12-23,2024-12-19,2024-12-19,0000-00-00,IMPORTACION A CONSUMO,NaN,CEC202477870199,CEC20247787019900010000,1,GUAYAQUIL MARITIMO,TRINIDAD AND TOBAGO,TRINIDAD AND TOBAGO,TRINIDAD AND TOBAGO,TTPTS-POINT LISAS,MARITIMO,0.0,NaN,"10,211.46",0.0,102.11,"10,313.57",STL0110110448,"790,551.44","10,313.59","28,789.00",0.0,"28,789.00",KILOGRAMO BRUTO,0.35,28.79,TM,354.7,"kg, Kilogramo",0.0,DOL,YARA SWITZERLAND LTD,CIF,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01902441: TORRES & TORRES AGENTES DE ADUANAS T...,SEAHORSE,02777787-REMAR REPRESENTACIONES MARITIMAS DEL ...,02777787-REMAR REPRESENTACIONES MARITIMAS DEL ...,NaN,0000-00-00,AFORO AUTOMATICO,0140-ACTIVIDADES DE SERVICIOS AGRICOLAS Y GANA...,KM 1 5 SOLAR 120 Y LOS ARCOS EDIF LOS A,NaN,NaN
1986,QUIMICA INDUSTRIAL MONTALVO AGUILAR QUIMASA S.A.,NaN,NaN,1790580202001,QUIMICA INDUSTRIAL MONTALVO AGUILAR QUIMASA S.A.,3102.10.10.00,0,1,Con un porcentaje de nitrógeno superior o igua...,"UREA, PARA USO AGRICOLA",HEXAGON,SIN MODELO,2820241003038095,1,NaN,2024-12-19,2024-12-02,2024-12-23,2024-12-19,2024-12-19,2024-12-26,IMPORTACION A CONSUMO,NaN,CEC202477870199,CEC20247787019900040000,EC-03,GUAYAQUIL MARITIMO,TRINIDAD AND TOBAGO,TRINIDAD AND TOBAGO,TRINIDAD AND TOBAGO,TTPTS-POINT LISAS,MARITIMO,0.0,NaN,"747,708.12",0.0,"4,300.29","752,008.44",2410511-0412,"747,708.12","840,653.44","2,026,172.00",0.0,"2,026,172.00",KILOGRAMO BRUTO,0.37,"2,026.17",TM,369.02,"kg, Kilogramo",0.0,DOL,HEXAGON TRADING AG,CFR,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,"747,708.12",0.0,"4,300.29","752,008.44","2,026,172.00",0.0,"840,653.44",0.0,0.0,0.0,NaN,NaN,01777833: CORADUANAS,SEAHORSE,02777787-REMAR REPRESENTACIONES MARITIMAS DEL ...,02777787-REMAR REPRESENTACIONES MARITIMAS DEL ...,NaN,0000-00-00,AFORO AUTOMATICO,5190-VENTA AL POR MAYOR DE OTROS PRODUCTOS,AMAZONAS N35-43 Y JUAN PABLO SANZ,NaN,NaN

Ahora, con una mascara escojo las columnas que me convienen.

In [76]:
data_total_2 = ['RAZON SOCIAL','FECHA EMBARQUE',
       'PAIS ORIGEN', 'VIA TRANSPORTE', 'PAIS DESTINO', 'FOB U$S', 'FLETE U$S', 'TOTAL KGS NETO']
data_total_raw_importaciones_urea = data_total_raw_importaciones_urea[data_total_2]

data_total_raw_importaciones_urea

,RAZON SOCIAL,FECHA EMBARQUE,PAIS ORIGEN,VIA TRANSPORTE,PAIS DESTINO,FOB U$S,FLETE U$S,TOTAL KGS NETO
0,DELCORP S.A.,2008-10-27,CHINA,MARITIMO,NO ESPECIFICADO,"359,550.25","76,110.00","575,000.00"
1,DUPOCSA PROTECTORES QUIMICOS PARA EL CAMPO S. A.,2009-02-18,RUSSIAN FEDERATION,CARRETERA,NO ESPECIFICADO,"75,664.81","6,800.00","240,000.00"
2,BANCO NACIONAL DE FOMENTO BNF,2009-03-02,VENEZUELA,MARITIMO,NO ESPECIFICADO,"5,781,583.00","748,095.50","20,648,510.00"
3,DUPOCSA PROTECTORES QUIMICOS PARA EL CAMPO S. A.,2009-03-04,PERU,CARRETERA,NO ESPECIFICADO,"76,244.80","4,800.00","240,000.00"
4,DUPOCSA PROTECTORES QUIMICOS PARA EL CAMPO S. A.,2009-03-10,RUSSIAN FEDERATION,CARRETERA,NO ESPECIFICADO,"76,144.81","6,400.00","240,000.00"
...,...,...,...,...,...,...,...,...
1982,PRECISAGRO S.A.,2024-12-02,TRINIDAD AND TOBAGO,MARITIMO,ECUADOR,"1,062,900.00",0.0,"3,039,258.00"
1983,PRECISAGRO S.A.,2024-12-02,TRINIDAD AND TOBAGO,MARITIMO,ECUADOR,"13,909.11",0.0,NaN
1984,YARECUADOR CIA LTDA,2024-12-02,TRINIDAD AND TOBAGO,MARITIMO,ECUADOR,"780,340.00",0.0,"2,228,789.00"
1985,YARECUADOR CIA LTDA,2024-12-02,TRINIDAD AND TOBAGO,MARITIMO,ECUADOR,"10,211.46",0.0,NaN
1986,QUIMICA INDUSTRIAL MONTALVO AGUILAR QUIMASA S.A.,2024-12-02,TRINIDAD AND TOBAGO,MARITIMO,ECUADOR,"747,708.12",0.0,"2,026,172.00"

Ahora revisare, columna a columna, los valores unicos y los NaN.

In [43]:
# Empezamos por FECHA EMBARQUE

In [77]:
data_total_raw_importaciones_urea['FECHA EMBARQUE'].value_counts()

FECHA EMBARQUE
0000-00-00    187
2024-04-28     12
2024-10-15     11
2023-12-23     11
2021-12-30     10
             ...
2016-04-25      1
2016-04-03      1
2016-04-06      1
2016-03-29      1
2016-12-17      1
Name: count, Length: 962, dtype: int64

In [78]:
data_total_raw_importaciones_urea['FECHA EMBARQUE'].isna().sum()

np.int64(0)

In [44]:
# PAIS ORIGEN

In [79]:
data_total_raw_importaciones_urea['PAIS ORIGEN'].value_counts()

PAIS ORIGEN
RUSSIAN FEDERATION      1233
NO ESPECIFICADO          243
CHINA                    212
GERMANY                   41
PERU                      39
UNITED STATES             34
VENEZUELA                 27
UKRAINE                   24
BELARUS                   20
FINLAND                   17
MALAYSIA                  13
INDONESIA                 12
COLOMBIA                  12
FRANCE                     9
LITHUANIA                  9
TRINIDAD AND TOBAGO        7
ESTONIA                    7
EGYPT                      7
LATVIA                     5
PAISES BAJOS               3
INDIA                      2
SPAIN                      2
BELGIUM                    2
NIGERIA                    2
UNITED ARAB EMIRATES       1
POLAND                     1
NEW ZEALAND                1
SWITZERLAND                1
ALGERIA                    1
Name: count, dtype: int64

In [80]:
data_total_raw_importaciones_urea['PAIS ORIGEN'].isna().sum()

np.int64(0)

In [12]:
# FOB U$S

In [81]:
data_total_raw_importaciones_urea['FOB U$S'].value_counts()

FOB U$S
46,950.00     12
14,518.06      6
20,480.00      5
26,400.00      5
29,030.00      5
              ..
13,845.00      1
167,361.98     1
130,100.00     1
216,870.20     1
747,708.12     1
Name: count, Length: 1803, dtype: int64

In [82]:
data_total_raw_importaciones_urea['FOB U$S'].isna().sum()

np.int64(0)

In [83]:
(data_total_raw_importaciones_urea['FOB U$S'] == 0).sum()

np.int64(0)

In [16]:
# FLETE U$S

In [84]:
data_total_raw_importaciones_urea['FLETE U$S'].isna().sum()

np.int64(0)

In [85]:
(data_total_raw_importaciones_urea['FLETE U$S'] == 0).sum()

np.int64(122)

In [61]:
# TOTAL KGS NETO

In [86]:
data_total_raw_importaciones_urea['TOTAL KGS NETO'].value_counts()

TOTAL KGS NETO
32,000.00       56
3,300,000.00    45
1,100,000.00    45
2,200,000.00    40
0.00            40
                ..
432,000.00       1
1,026,000.00     1
965,700.00       1
978.00           1
2,026,172.00     1
Name: count, Length: 837, dtype: int64

In [87]:
data_total_raw_importaciones_urea['TOTAL KGS NETO'].isna().sum()

np.int64(205)

Me he dado cuenta que:

-En FLETE tengo unos 0.0 y 0.00

-En TOTAL KGS NETO tengo Unos 0.00 y unos NaN

-En PAIS DE ORIGEN, tengo paises no especificados.

In [88]:
data_total_raw_importaciones_urea.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1987 entries, 0 to 1986
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   RAZON SOCIAL    1987 non-null   object
 1   FECHA EMBARQUE  1987 non-null   object
 2   PAIS ORIGEN     1987 non-null   object
 3   VIA TRANSPORTE  1987 non-null   object
 4   PAIS DESTINO    1957 non-null   object
 5   FOB U$S         1987 non-null   object
 6   FLETE U$S       1987 non-null   object
 7   TOTAL KGS NETO  1782 non-null   object
dtypes: object(8)
memory usage: 124.3+ KB

Empiezo por rellenar los NaN y 0 de las columnas FLETE y KGS. Me doy cuenta que estas columnas estan como objetos. Tengo que pasarlas a int para poder modificarlas. Primero extraigo las comas y cualquier signo de dolar (porsiacaso).

In [89]:
# Defino las columnas a limpiar
columns_to_clean = ['FOB U$S', 'FLETE U$S', 'TOTAL KGS NETO']

# Convierto los valores
for column in columns_to_clean:
    data_total_raw_importaciones_urea.loc[:, column] = (
        data_total_raw_importaciones_urea[column]
        .str.replace('$', '', regex=False)  
        .str.replace(',', '', regex=False) 
        .str.strip()                       
    )

Ahora cambio las filas FILETE U$S, FOB U$S Y TOTAL KGS NETO a numerico.

In [90]:
data_total_raw_importaciones_urea[['FLETE U$S', 'FOB U$S', 'TOTAL KGS NETO']] = data_total_raw_importaciones_urea[['FLETE U$S', 'FOB U$S', 'TOTAL KGS NETO']].apply(pd.to_numeric, errors='coerce')

/var/folders/9d/njcmv3bs67bgg_6p6s5pyjsw0000gn/T/ipykernel_3028/432266307.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total_raw_importaciones_urea[['FLETE U$S', 'FOB U$S', 'TOTAL KGS NETO']] = data_total_raw_importaciones_urea[['FLETE U$S', 'FOB U$S', 'TOTAL KGS NETO']].apply(pd.to_numeric, errors='coerce')

Siendo el comentario, verifico que las columnas se hayan cambiado a numerico.

In [91]:
data_total_raw_importaciones_urea.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1987 entries, 0 to 1986
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   RAZON SOCIAL    1987 non-null   object
 1   FECHA EMBARQUE  1987 non-null   object
 2   PAIS ORIGEN     1987 non-null   object
 3   VIA TRANSPORTE  1987 non-null   object
 4   PAIS DESTINO    1957 non-null   object
 5   FOB U$S         1987 non-null   float64
 6   FLETE U$S       1862 non-null   float64
 7   TOTAL KGS NETO  1782 non-null   float64
dtypes: float64(3), object(5)
memory usage: 124.3+ KB

Ahora reemplazo los NaN y 0 por el MEAN de su razon social especifica.

In [94]:
columns = ['FLETE U$S', 'TOTAL KGS NETO']

for col in columns:
    means_by_razon = data_total_raw_importaciones_urea[data_total_raw_importaciones_urea[col] > 0].groupby('RAZON SOCIAL')[col].mean()
    
    data_total_raw_importaciones_urea.loc[:, col] = data_total_raw_importaciones_urea[col].fillna(data_total_raw_importaciones_urea['RAZON SOCIAL'].map(means_by_razon))
    
    # Ahora, reemplazo los ceros con el promedio por RAZON SOCIAL
    data_total_raw_importaciones_urea.loc[data_total_raw_importaciones_urea[col] == 0, col] = (data_total_raw_importaciones_urea.loc[data_total_raw_importaciones_urea[col] == 0, 'RAZON SOCIAL'].map(means_by_razon))

# Por dudas, erifico
for col in columns:
    print(f"\n{col}:")
    print(f"NaN: {data_total_raw_importaciones_urea[col].isna().sum()}")
    print(f"0: {(data_total_raw_importaciones_urea[col] == 0).sum()}")

FLETE U$S:
NaN: 0
0: 0

TOTAL KGS NETO:
NaN: 0
0: 0

Con los que me sale como pais de origen no especificado, siendo que es un valor representativo, voy a distribuir estos valores entre los 6 paises principales.

In [95]:
data_total_raw_importaciones_urea[data_total_raw_importaciones_urea['PAIS ORIGEN'] == 'NO ESPECIFICADO']

,RAZON SOCIAL,FECHA EMBARQUE,PAIS ORIGEN,VIA TRANSPORTE,PAIS DESTINO,FOB U$S,FLETE U$S,TOTAL KGS NETO
290,QUIMICA INDUSTRIAL MONTALVO AGUILAR QUIMASA S.A.,2012-11-30,NO ESPECIFICADO,MARITIMO,ECUADOR,222794.00,33000.00,550000.0
291,IMPORTADORA INDUSTRIAL AGRICOLA DEL MONTE,2012-12-08,NO ESPECIFICADO,MARITIMO,ECUADOR,153291.84,12885.00,312000.0
292,SOLVESA ECUADOR S.A,2012-12-16,NO ESPECIFICADO,MARITIMO,ECUADOR,282403.62,18502.00,637480.0
293,FERTILIZANTES DEL PACIFICO FERPACIFIC S.A.,2012-12-30,NO ESPECIFICADO,MARITIMO,ECUADOR,133980.00,20880.00,348000.0
294,DELCORP S.A.,2012-12-30,NO ESPECIFICADO,MARITIMO,ECUADOR,870812.12,109672.75,2099000.0
...,...,...,...,...,...,...,...,...
543,DELCORP S.A.,2014-08-13,NO ESPECIFICADO,MARITIMO,ECUADOR,98761.00,26000.00,273000.0
544,INTERAMERICANA DE PRODUCTOS QUIMICOS DEL ECUAD...,2014-08-18,NO ESPECIFICADO,MARITIMO,ECUADOR,160398.00,33516.00,479864.0
545,INTERAMERICANA DE PRODUCTOS QUIMICOS DEL ECUAD...,2014-08-18,NO ESPECIFICADO,MARITIMO,ECUADOR,369869.50,71294.08,1096832.0
546,DELCORP S.A.,2014-08-17,NO ESPECIFICADO,MARITIMO,ECUADOR,45582.00,13310.00,126000.0
547,DELCORP S.A.,2014-07-31,NO ESPECIFICADO,MARITIMO,ECUADOR,49776.65,4985.48,55000.0

In [98]:

no_spec_mask = data_total_raw_importaciones_urea['PAIS ORIGEN'] == 'NO ESPECIFICADO'
total_no_spec = no_spec_mask.sum()

# Escojo los paises entre los que distibuire
target_countries = ['RUSSIAN FEDERATION', 'CHINA', 'UNITED STATES', 'PERU', 'MALAYSIA', 'INDONESIA']

# Divido entre los 6
records_per_country = total_no_spec // 6

# Hacemos las asignasiones random
random_assignments = np.repeat(target_countries, records_per_country)

# Cualquiera que quede lo agregamos random
remainder = total_no_spec - len(random_assignments)
if remainder > 0:
    random_assignments = np.concatenate([
        random_assignments,
        np.random.choice(target_countries, remainder)
    ])

# Hacemos shuffle a los assigments
np.random.shuffle(random_assignments)

# Reemplazo los NO ESPECIFICADO con random
data_total_raw_importaciones_urea.loc[no_spec_mask, 'PAIS ORIGEN'] = random_assignments

# Verificamos distribucion
print("Distribucion:")
for country in target_countries:
    count = len(data_total_raw_importaciones_urea[data_total_raw_importaciones_urea['PAIS ORIGEN'] == country])
    print(f"{country}: {count}")

print("'NO ESPECIFICADO':", 
      len(data_total_raw_importaciones_urea[data_total_raw_importaciones_urea['PAIS ORIGEN'] == 'NO ESPECIFICADO']))

Distribucion:
RUSSIAN FEDERATION: 1273
CHINA: 252
UNITED STATES: 76
PERU: 79
MALAYSIA: 54
INDONESIA: 52
'NO ESPECIFICADO': 0

Reviso el valor de las filas con fechas nulas y si no es significativo, las borro

In [99]:
len(data_total_raw_importaciones_urea[data_total_raw_importaciones_urea['FECHA EMBARQUE'] == '0000-00-00'])

187

In [100]:
data_total_raw_importaciones_urea = data_total_raw_importaciones_urea[data_total_raw_importaciones_urea['FECHA EMBARQUE'] != '0000-00-00']

Borro las razones sociales

In [101]:
data_total_3 = ['FECHA EMBARQUE',
       'PAIS ORIGEN', 'FOB U$S', 'TOTAL KGS NETO']
resultado_data_total_importaciones_urea = data_total_raw_importaciones_urea[data_total_3]

resultado_data_total_importaciones_urea

     FECHA EMBARQUE          PAIS ORIGEN     FOB U$S  TOTAL KGS NETO
0        2008-10-27                CHINA   359550.25        575000.0
1        2009-02-18   RUSSIAN FEDERATION    75664.81        240000.0
2        2009-03-02            VENEZUELA  5781583.00      20648510.0
3        2009-03-04                 PERU    76244.80        240000.0
4        2009-03-10   RUSSIAN FEDERATION    76144.81        240000.0
...             ...                  ...         ...             ...
1982     2024-12-02  TRINIDAD AND TOBAGO  1062900.00       3039258.0
1983     2024-12-02  TRINIDAD AND TOBAGO    13909.11       2764157.8
1984     2024-12-02  TRINIDAD AND TOBAGO   780340.00       2228789.0
1985     2024-12-02  TRINIDAD AND TOBAGO    10211.46       2782829.8
1986     2024-12-02  TRINIDAD AND TOBAGO   747708.12       2026172.0

[1800 rows x 4 columns]

Sacamos el total de cuanto ha importado cada pais.

In [ ]:

resumen_por_pais = resultado_data_total_importaciones_urea.groupby('PAIS ORIGEN').agg({'FOB U$S': 'sum','TOTAL KGS NETO': 'sum'}).reset_index()

# Renombrar columnas para el pie chart que crearemos
resumen_por_pais.columns = ['País', 'FOB Total', 'KGS NETO Total']

resumen_por_pais = resumen_por_pais.sort_values('FOB Total', ascending=False)

resumen_por_pais

                    País     FOB Total  KGS NETO Total
20    RUSSIAN FEDERATION  6.111654e+08    2.005964e+09
27             VENEZUELA  1.310475e+08    3.626484e+08
3                  CHINA  1.193653e+08    4.447610e+08
24               UKRAINE  3.965944e+07    1.107855e+08
11             INDONESIA  2.444779e+07    7.143645e+07
18                  PERU  2.426616e+07    7.014828e+07
26         UNITED STATES  2.156188e+07    5.953818e+07
1                BELARUS  1.964173e+07    8.242050e+07
14              MALAYSIA  1.902323e+07    5.752314e+07
13             LITHUANIA  8.477337e+06    4.563021e+07
7                FINLAND  6.667015e+06    2.230346e+07
12                LATVIA  4.529588e+06    1.866508e+07
6                ESTONIA  4.247441e+06    1.338396e+07
23   TRINIDAD AND TOBAGO  3.629594e+06    1.554121e+07
5                  EGYPT  3.551378e+06    1.548214e+07
16               NIGERIA  2.503542e+06    8.967470e+06
2                BELGIUM  1.387137e+06    5.529000e+06
25  UNITED ARAB EMIRATES  5.247746e+05    1.000000e+06
10                 INDIA  3.075496e+05    3.138479e+05
15           NEW ZEALAND  2.851594e+05    9.450000e+05
0                ALGERIA  2.290410e+05    9.000000e+05
22           SWITZERLAND  1.203056e+05    4.930000e+05
9                GERMANY  1.032956e+05    3.609284e+05
17          PAISES BAJOS  3.177202e+04    7.379200e+04
8                 FRANCE  2.026416e+04    9.917740e+04
19                POLAND  9.930000e+03    3.000000e+04
4               COLOMBIA  7.929350e+03    7.730510e+04
21                 SPAIN  1.558800e+02    2.546229e+04

In [168]:
resumen_por_pais.to_csv('Data_2/resumen_por_pais.csv', index=False)

Cambio el nombre de la columna de fecha para que pueda concidir con los otros Data Sets

In [104]:
resultado_data_total_importaciones_urea = resultado_data_total_importaciones_urea.rename(columns={'FECHA EMBARQUE': 'FECHA'})

Ahora guardo el csv

In [105]:
resultado_data_total_importaciones_urea.to_csv('Data_2/resultado_por_dia_total_urea.csv')

Ahora quiero saber los valores por mes/año.

In [106]:
resultado_data_total_importaciones_urea

           FECHA          PAIS ORIGEN     FOB U$S  TOTAL KGS NETO
0     2008-10-27                CHINA   359550.25        575000.0
1     2009-02-18   RUSSIAN FEDERATION    75664.81        240000.0
2     2009-03-02            VENEZUELA  5781583.00      20648510.0
3     2009-03-04                 PERU    76244.80        240000.0
4     2009-03-10   RUSSIAN FEDERATION    76144.81        240000.0
...          ...                  ...         ...             ...
1982  2024-12-02  TRINIDAD AND TOBAGO  1062900.00       3039258.0
1983  2024-12-02  TRINIDAD AND TOBAGO    13909.11       2764157.8
1984  2024-12-02  TRINIDAD AND TOBAGO   780340.00       2228789.0
1985  2024-12-02  TRINIDAD AND TOBAGO    10211.46       2782829.8
1986  2024-12-02  TRINIDAD AND TOBAGO   747708.12       2026172.0

[1800 rows x 4 columns]

Borramos las columnas que no son necesarias

In [107]:
data_total_4 = ['FECHA', 'FOB U$S', 'TOTAL KGS NETO']
importaciones_urea_simplificadas = resultado_data_total_importaciones_urea[data_total_4]

importaciones_urea_simplificadas

           FECHA     FOB U$S  TOTAL KGS NETO
0     2008-10-27   359550.25        575000.0
1     2009-02-18    75664.81        240000.0
2     2009-03-02  5781583.00      20648510.0
3     2009-03-04    76244.80        240000.0
4     2009-03-10    76144.81        240000.0
...          ...         ...             ...
1982  2024-12-02  1062900.00       3039258.0
1983  2024-12-02    13909.11       2764157.8
1984  2024-12-02   780340.00       2228789.0
1985  2024-12-02    10211.46       2782829.8
1986  2024-12-02   747708.12       2026172.0

[1800 rows x 3 columns]

Ahora si atacamos

In [109]:
# Hacemos que la fecha sea datetime
importaciones_urea_simplificadas['FECHA'] = pd.to_datetime(importaciones_urea_simplificadas['FECHA'], format="%Y-%m-%d")   

# Extraemos año y mes
importaciones_urea_simplificadas['Año'] = importaciones_urea_simplificadas['FECHA'].dt.year
importaciones_urea_simplificadas['Mes'] = importaciones_urea_simplificadas['FECHA'].dt.month

# Creamos DataFrame para FOB U$S por mes y año
fob_por_mes = importaciones_urea_simplificadas.groupby(['Año', 'Mes'])['FOB U$S'].sum().reset_index()
fob_por_mes.columns = ['Año', 'Mes', 'FOB U$S Total']
fob_por_mes = fob_por_mes.sort_values(['Año', 'Mes'])

# Creamos DataFrame para TOTAL KGS NETO por mes y año
kgs_por_mes = importaciones_urea_simplificadas.groupby(['Año', 'Mes'])['TOTAL KGS NETO'].sum().reset_index()
kgs_por_mes.columns = ['Año', 'Mes', 'TOTAL KGS NETO']
kgs_por_mes = kgs_por_mes.sort_values(['Año', 'Mes'])

/var/folders/9d/njcmv3bs67bgg_6p6s5pyjsw0000gn/T/ipykernel_3028/1096727660.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  importaciones_urea_simplificadas['FECHA'] = pd.to_datetime(importaciones_urea_simplificadas['FECHA'], format="%Y-%m-%d")

In [111]:
fob_por_mes

      Año  Mes  FOB U$S Total
0    2008   10      359550.25
1    2009    2       75664.81
2    2009    3    12169329.36
3    2009    4     4232816.50
4    2009    5     3604214.75
..    ...  ...            ...
166  2024    8      511807.44
167  2024    9     7894563.62
168  2024   10    10755710.00
169  2024   11     3101462.42
170  2024   12     3629593.69

[171 rows x 3 columns]

In [113]:
fob_por_mes.to_csv('/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data_2/fob_kgs/fob_por_mes.csv')

In [114]:
fob_por_mes_ordenado = fob_por_mes.sort_values('FOB U$S Total', ascending=False)

In [115]:
fob_por_mes_ordenado.to_csv('/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data_2/fob_kgs/fob_por_mes_ordenado.csv')

In [116]:
kgs_por_mes

      Año  Mes  TOTAL KGS NETO
0    2008   10    5.750000e+05
1    2009    2    2.400000e+05
2    2009    3    4.270699e+07
3    2009    4    1.650221e+07
4    2009    5    1.686980e+07
..    ...  ...             ...
166  2024    8    1.598000e+06
167  2024    9    2.621726e+07
168  2024   10    3.053837e+07
169  2024   11    1.086499e+07
170  2024   12    1.554121e+07

[171 rows x 3 columns]

In [117]:
kgs_por_mes.to_csv('/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data_2/fob_kgs/kgs_por_mes.csv')

In [118]:
kgs_por_mes_ordenado = kgs_por_mes.sort_values('TOTAL KGS NETO', ascending=False)
kgs_por_mes_ordenado

      Año  Mes  TOTAL KGS NETO
77   2016    4    7.359422e+07
96   2017   11    7.030546e+07
69   2014   11    6.888001e+07
158  2023   12    6.571547e+07
57   2013   11    5.940054e+07
..    ...  ...             ...
18   2010    8    4.000000e+04
52   2013    6    3.393000e+04
71   2015    1    2.970000e+04
143  2022    8    1.286700e+03
62   2014    4    2.756700e+02

[171 rows x 3 columns]

In [119]:
kgs_por_mes_ordenado.to_csv('/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data_2/fob_kgs/kgs_por_mes_ordenado.csv')

In [120]:
# Uno los dos data frames usando año y mes como clave
fob_kgs_por_mes = pd.merge(
    fob_por_mes,         
    kgs_por_mes,         
    on=['Año', 'Mes'],   
    how='inner'          
)

In [121]:
fob_kgs_por_mes

      Año  Mes  FOB U$S Total  TOTAL KGS NETO
0    2008   10      359550.25    5.750000e+05
1    2009    2       75664.81    2.400000e+05
2    2009    3    12169329.36    4.270699e+07
3    2009    4     4232816.50    1.650221e+07
4    2009    5     3604214.75    1.686980e+07
..    ...  ...            ...             ...
166  2024    8      511807.44    1.598000e+06
167  2024    9     7894563.62    2.621726e+07
168  2024   10    10755710.00    3.053837e+07
169  2024   11     3101462.42    1.086499e+07
170  2024   12     3629593.69    1.554121e+07

[171 rows x 4 columns]

In [122]:
fob_kgs_por_mes.to_csv('/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data_2/fob_kgs/fob_kgs_por_mes.csv')

In [123]:
# Uno los ordenados
fob_kgs_por_mes_ordenado = pd.merge(
    fob_por_mes_ordenado,        
    kgs_por_mes_ordenado,        
    on=['Año', 'Mes'],   
    how='inner'          
)

In [124]:
fob_kgs_por_mes_ordenado

      Año  Mes  FOB U$S Total  TOTAL KGS NETO
0    2021   12    26534264.41    3.535902e+07
1    2022   11    21028746.69    3.809373e+07
2    2011    8    20538153.84    4.072621e+07
3    2014   11    20307202.00    6.888001e+07
4    2013   11    19624307.13    5.940054e+07
..    ...  ...            ...             ...
166  2014    7       49776.65    5.500000e+04
167  2015    1       14518.06    2.970000e+04
168  2010    8       12000.00    4.000000e+04
169  2022    8         584.29    1.286700e+03
170  2014    4          93.90    2.756700e+02

[171 rows x 4 columns]

In [125]:
fob_kgs_por_mes_ordenado.to_csv('/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data_2/fob_kgs/fob_kgs_por_mes_ordenado.csv')

Aqui termino con las importaciones

<h1>Data importaciones todos los fertilizantes 2024</h1>

En este punto, he querido extraer las importaciones de todos los fertilizantes (no solo de urea), para poder visualizar el mercado en el ultimo año, 2024.

In [151]:
fertilizantes_2024 = pd.read_csv('/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data /Importaciones Todos Fertilizantes 2024/fetilizantes 2024.csv')

In [152]:
fertilizantes_2024.head(25)

,RAZON SOCIAL,POTENCIAL UNO,NOMBRE COMERCIAL,RUC,CONSIGNATARIO,POSICION ARANCELARIA,CODIGO COMPLEMENTARIO,CODIGO SUPLEMENTARIO,DESCRIPCION POSICION,DESCRIPCION DEL DESPACHO,MARCA,MODELO,REFRENDO,ITEM,DAU,FECHA DESPACHO,FECHA EMBARQUE,FECHA LLEGADA,FECHA LIQUIDACION,FECHA PAGO,FECHA SALIDA ALMACEN,REGIMEN,NUMERO MANIFIESTO,MANIFIESTO,CODIGO DOCUMENTO TRANSPORTE,DOCUMENTO TRANSPORTE,ADUANA,PAIS ORIGEN,PAIS PROCEDENCIA,PAIS EMBARQUE,PUERTO EMBARQUE,VIA TRANSPORTE,CONTENEDORES,DEPOSITO,FOB U$S,FLETE U$S,SEGURO U$S,CIF U$S,FACTURA,VALOR FACTURA U$S,BASE IMPONIBLE U$S,KGS NETO,KGS BRUTO,UNIDADES,TIPO UNIDAD,PRECIO UNITARIO U$S,CANTIDAD COMERCIAL,UNIDAD COMERCIAL,PRECIO UNITARIO COMERCIAL U$S,TIPO UNIDAD NOMENCLADOR,ADVAL,MONEDA,EMBARCADOR,INCOTERM,CODIGO LIBERACION,ESTADO MERCADERIA,CLASE MERCADERIA,PAIS DESTINO,TOTAL FOB U$S,TOTAL FLETE U$S,TOTAL SEGURO U$S,TOTAL CIF U$S,TOTAL KGS NETO,TOTAL KGS BRUTO,TOTAL BASE IMPONIBLE,TOTAL CANTIDAD BULTOS,TOTAL AJUSTES,TOTAL OTROS AJUSTES,CLASE,VERIFICADOR,AGENTE AFIANZADO,NAVE,AGENCIA TRANSPORTE,EMPRESA TRANSPORTE,AFORADOR,FECHA AFORO,TIPO AFORO,ACTIVIDAD PRINCIPAL DEL IMPORTADOR,DIRECCION DEL IMPORTADOR,DIRECCION DEL CONSIGNATARIO,CONSOLIDADORA
0,SOLVESA ECUADOR S.A,NaN,NaN,990839557001,SOLVESA ECUADOR S.A,3102.50.00.00,0,0,Nitrato de sodio,"NITRATO DE SODIO, NITRATO DE SODIO",SIN MARCA,SMODELO,2820241000000164,1,NaN,2024-01-01,2023-12-10,2023-12-25,2024-01-01,2024-01-02,2024-01-02,IMPORTACION A CONSUMO,NaN,CEC2023MAEU0502,CEC2023MAEU050291500001,HLCUSCL231124355,GUAYAQUIL MARITIMO,CHILE,CHILE,CHILE,CLIQQ-IQUIQUE,MARITIMO,8.0,05907400-INARPI S.A.,"154,400.00",0.00,153.00,"154,553.00",423,"154,400.00","170,153.00","200,000.00",0.0,"200,000.00",KILOGRAMO BRUTO,0.77,"200,000.00",KG,0.77,"kg, Kilogramo",0.0,DOL,COSAYACH EXPORTADORA S A,CFR,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,"154,400.00",0.00,153.00,"154,553.00","200,000.00",0.0,"170,153.00",0.0,0.00,0.0,NaN,NaN,01777779: JIMENEZ QUIROZ BORIS LENIN,MAERSK ACADIA,NaN,02777827-HAPAG-LLOYD ECUADOR S.A.,NaN,0000-00-00,AFORO AUTOMATICO,5190-VENTA AL POR MAYOR DE OTROS PRODUCTOS,"CASUARINA 100 Y VIA A DAULE, GUAYAQUIL",NaN,TOLEPU S.A.
1,BOSCHETTI S.A.,NaN,NaN,992392703001,TO THE ORDER OF BOSCHETTI S.A.,3102.10.90.00,0,1,Las demás,"HEMOFAST, HEMOFAST FERTILIZANTES INORGANICOS",SIN MARCA,HEMOFAST BK1813,2820241000003590,1,NaN,2024-01-02,2023-11-16,2023-12-30,2024-01-02,2024-01-02,2024-01-05,IMPORTACION A CONSUMO,NaN,CEC2023MSCU0480,CEC2023MSCU048001870000,MEDUQP083320,GUAYAQUIL MARITIMO,ITALY,ITALY,ITALY,ITSPE-LA SPEZIA,MARITIMO,10.0,05909025-CONTECON GUAYAQUIL S.A.,"264,671.41",0.00,"2,806.60","267,478.00",2023-FEST-0000413,"264,671.41","283,466.19","239,880.00",0.0,"243,080.00",KILOGRAMO BRUTO,1.09,"239,880.00",KG,1.10,"kg, Kilogramo",0.0,DOL,TEN COM GROUP,CFR,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,"264,671.41",0.00,"2,806.60","267,478.00","239,880.00",0.0,"283,466.19",0.0,0.00,0.0,NaN,NaN,01903052: MOREIRA NARANJO JAIME MAURO,MSC KATYA R.,02908390-MEDITERRANEAN SHIPPING COMPANY DEL EC...,02908390-MEDITERRANEAN SHIPPING COMPANY DEL EC...,NaN,0000-00-00,AFORO AUTOMATICO,5190-VENTA AL POR MAYOR DE OTROS PRODUCTOS,AV. JUAN TANCA MARENGO KM 0.5 211EDIFICIO FAMO...,NaN,NaN
2,BOSCHETTI S.A.,NaN,NaN,992392703001,BOSCHETTI S.A,3102.10.90.00,0,1,Las demás,"AZOFERT 55, AZOFERT FERTILIZANTE ORGANICO",SIN MARCA,SIN MODELO,2820241000003594,1,NaN,2024-01-02,2023-11-22,2023-12-30,2024-01-02,2024-01-02,2024-01-08,IMPORTACION A CONSUMO,NaN,CEC2023MSCU0480,CEC2023MSCU048001200000,MEDUO6178885,GUAYAQUIL MARITIMO,ITALY,PAISES BAJOS,PAISES BAJOS,NLRTM-ROTTERDAM,MARITIMO,12.0,05909025-CONTECON GUAYAQUIL S.A.,"181,204.70",0.00,129.82,"181,334.53",2023-FEST-0000423,"181,204.70","194,316.61","308,233.00",0.0,"311,353.00",KILOGRAMO BRUTO,0.58,"308,233.00",KG,0.59,"kg, Kilogramo",0.0,DOL,TEN COM GROUP SRL,CFR,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,"181,204.70",0.00,129.82,"181,334.53","308,233.00",0.0,"194,316.61",0.0,0.00,0.0,NaN,NaN,01900022: SOLUCIONES INTEGRALES DE LOGISTICA Y...,MSC KATYA R.,02908390-MEDITERRANEAN SHIPPING COMPANY DEL EC...,02908390-MEDITERRANEAN SHIPPING COMPANY DEL EC...,NaN,0000-00-00,AFORO AUTOMATICO,5190-VENTA AL POR MAYOR DE OTROS PRODUCTOS,AV. JUAN TANCA MARENGO KM 0.5 211EDIFICIO FAMO...,NaN,NaN
3,FERTILIZANTES DEL PACIFICO FERPACIFIC S.A.,NaN,NaN,991441336001,FERTILIZANTES DEL PACIFICO FERPACIFIC S.A.,3102.60.00.00,0,1,Sales dobles y mezclas entre si de nitrato de ...,"CALCIUM NITRATE GRANULAR, FERTILIZANTE -100 TO...",WEGROW,FERTILIZANTE DE USO AGRICOLA,2820241000003623,1,NaN,2024-01-02,2023-11-09,2023-12-30,2024-01-02,2024-01-03,2024-01-20,IMPORTACION A CONSUMO,NaN,CEC2023TBNA5015,CEC2023TBNA501500070000,5R7042XGG042,GUAYAQUIL MARITIMO,CHINA,CHINA,CHINA,CNXGG-XINGANG,MARITIMO,0.0,05909025-CONTECON GUAYAQUIL S.A.,"27,000.00",0.00,44.80,"27,044.80",5001563,"27,000.00","32,044.80","100,000.00",0.0,"100,400.00",KILOGRAMO BRUTO,0.27,"100,000.00",KG,0.27,"kg, Kilogramo",0.0,DOL,WEGROW AG,CFR,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,"27,000.00",0.00,44.80,"27,044.80","100,000.00",0.0,"32,044.80",0.0,0.00,0.0,NaN,NaN,01777837: VARYMPEX S.A.,PACIFIC NEXUS,NaN,02908903-AGENCIA TECNICO MARITIMA TECNISEA C. ...,MACUNA-ACU??A ZHINGRI MARIA FERNANDA,0000-00-00,AFORO FISICO INTRUSIVO,0140-ACTIVIDADES DE SERVICIOS AGRICOLAS Y GANA...,"KM 16,5 VIA A DAULE",NaN,NaN
4,BOSCHETTI S.A.,NaN,NaN,992392703001,BOSCHETTI S.A,3102.10.90.00,0,1,Las demás,"AZOFERT 55, IN 156 BIG BAGS",SIN MARCA,AZOFERT 55,2820241000003776,1,NaN,2024-01-02,2023-11-29,2023-12-30,2024-01-02,2024-01-02,2024-01-04,IMPORTACION A CONSUMO,NaN,CEC2023MSCU0480,CEC2023MSCU048001280000,MEDUO6179735,GUAYAQUIL MARITIMO,ITALY,PAISES BAJOS,PAISES BAJOS,NLRTM-ROTTERDAM,MARITIMO,12.0,05909025-CONTECON GUAYAQUIL S.A.,"183,255.36",0.00,"1,962.37","185,217.73",2023-FEST-0000438,"183,255.36","198,199.81","311,488.00",0.0,"314,608.00",KILOGRAMO BRUTO,0.58,"311,488.00",KG,0.59,"kg, Kilogramo",0.0,DOL,VIA PER FORMIGINE 45D,CFR,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,"183,255.36",0.00,"1,962.37","185,217.73","311,488.00",0.0,"198,199.81",0.0,0.00,0.0,NaN,NaN,01903052: MOREIRA NARANJO JAIME MAURO,MSC KATYA R.,02908390-MEDITERRANEAN SHIPPING COMPANY DEL EC...,02908390-MEDITERRANEAN SHIPPING COMPANY DEL EC...,NaN,0000-00-00,AFORO AUTOMATICO,5190-VENTA AL POR MAYOR DE OTROS PRODUCTOS,AV. JUAN TANCA MARENGO KM 0.5 211EDIFICIO FAMO...,NaN,NaN
5,FERTILIZANTES DEL PACIFICO FERPACIFIC S.A.,NaN,NaN,991441336001,FERTILIZANTES DEL PACIFICO FERPACIFIC S.A.,3102.60.00.00,0,1,Sales dobles y mezclas entre si de nitrato de ...,"NITRATO DE CALCIO, FERTILIZANTE -200 TONELADAS",WEGROW,FERTILIZANTE DE USO AGRICOLA,2820241000004008,1,NaN,2024-01-02,2023-11-09,2023-12-30,2024-01-02,2024-01-02,2024-01-19,IMPORTACION A CONSUMO,NaN,CEC2023TBNA5015,CEC2023TBNA501500130000,5R7042XGG048,GUAYAQUIL MARITIMO,CHINA,CHINA,CHINA,CNXGG-XINGANG,MARITIMO,0.0,05909025-CONTECON GUAYAQUIL S.A.,"48,400.00",0.00,79.52,"48,479.52",5001569,"48,400.00","56,879.52","200,000.00",0.0,"200,480.00",KILOGRAMO BRUTO,0.24,"200,000.00",KG,0.24,"kg, Kilogramo",0.0,DOL,WEGROW AG,CFR,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,"48,400.00",0.00,79.52,"48,479.52","200,000.00",0.0,"56,879.52",0.0,0.00,0.0,NaN,NaN,01777837: VARYMPEX S.A.,PACIFIC NEXUS,NaN,02908903-AGENCIA TECNICO MARITIMA TECNISEA C. ...,JVZAMORA-ZAMORA ESCOBAR JOFFRE VICENTE,0000-00-00,AFORO FISICO INTRUSIVO,0140-ACTIVIDADES DE SERVICIOS AGRICOLAS Y GANA...,"KM 16,5 VIA A DAULE",NaN,NaN
6,MORALVA CLTDA,NaN,NaN,992339640001,MORALVA C. LTDA.,3102.21.00.00,0,1,Sulfato de amonio,"SULFATO DE AMONIO GRANULAR, SULFATO DE AMONIO ...",SIN MARCA,SIN MODELO,2820241000004566,1,NaN,2024-01-02,2023-11-09,2023-12-30,2024-01-02,2024-01-02,2024-01-06,IMPORTACION A CONSUMO,NaN,CEC2023TBNA5015,CEC2023TBNA501500150000,5R7042XGG050,GUAYAQUIL MARITIMO,CHINA,CHINA,CHINA,CNTSN-TIANJIN,MARITIMO,0.0,05909025-CONTECON GUAYAQUIL S.A.,"127,800.00",0.00,225.00,"128,025.00",12199-72,"127,800.00","150,225.00","600,000.00",0.0,"600,000.00",KILOGRAMO BRUTO,0.21,"600,000.00",KG,0.21,"kg, Kilogramo",0.0,DOL,STAR GRACE MINING CO LTD.,CFR,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,"127,800.00",0.00,225.00,"128,025.00","600,000.00",0.0,"150,225.00",0.0,0.00,0.0,NaN,NaN,01901316: ORGANIZACION COMERCIAL Y ADUANERA MA...,PACIFIC NEXUS,NaN,02908903-AGENCIA TECNICO MARITIMA TECNISEA C. ...,NaN,0000-00-00,AFORO AUTOMATICO,9993-OTROS,VIA A LA COSTA KM 6 1/2 LA VISTA SAN EDUARDO C...,NaN,NaN
7,AGRICOLA Y QUIMICA NACIONAL DEL COTOPAXI AGRON...,NaN,NaN,590060569001,AGRICOLA Y QUIMICA NACIONAL DEL COTOPAXI AGRON...,3102.90.90.00,0,1,Los demás,"N HIB CALCIUM, X 1000 LT",SIN MARCA,SIN MODELO,2820241000007131,8,NaN,2024-01-02,2023-12-28,2023-12-31,2024-01-02,2024-01-02,2024-01-03,IMPORTACION A CONSUMO,NaN,CEC2023ONEU0048,CEC2023ONEU004810278557,ONEYLIMD20948700,GUAYAQUIL MARITIMO,PERU,PERU,PERU,PECLL-CALLAO,MARITIMO,2.0,05907400-INARPI S.A.,"9,010.00",128.67,19.46,"9,158.13",F003-0000174,"99,778.83","9,158.13","13,900.00",0.0,"14,496.66",KILOGRAMO BRUTO,0.62,"10,000.00",L,0.90,"kg, Kilogramo",0.0,DOL,STOLLER PERU SA,FOB,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,"99,778.83",450.01,215.51,"100,444.35","48,613.28",0.0,"100,444.35",0.0,0.00,0.0,NaN,NaN,01777779: JIMENEZ QUIROZ BORIS LENIN,ESSENCE,NaN,02777845-OCEAN NETWORK EXPRESS (ECUADOR) ONEEC...,PALOPEZ-LOPEZ POTES PAMELA ELIZABETH,0000-00-00,AFORO DOCUMENTAL,5190-VENTA AL POR MAYOR DE OTROS PRODUCTOS,JOSEGUANGO BAJO / PANAMERICANA NORTE S/N Y SEC...,NaN,AIR MAINLAND & SEA CARGO SERVICE S.A. AMSECARGO
8,AGRICOLA Y QUIMICA NACIONAL DEL COTOPAXI AGRON...,NaN,NaN,590060569001,AGRICOLA Y QUIMICA NACIONAL DEL COTOPAXI AGRON...,3102.90.90.00,0,1,Los demás,"AQUA CAL, X 1000 LT",SIN MARCA,SIN MODELO,2820241000007131,9,NaN,2024-01-02,2023-12-28,2023-12-31,2024-01-02,2024-01-02,2024-01-03,IMPORTACION A CONSUMO,NaN,CEC2023ONEU0048,CEC2023ONEU004810278557,ONEYLIMD20948700,GUAYAQUIL MARITIMO,PERU,PERU,PERU,PECLL-CALLAO,MARITIMO,2.0,05907400-INARPI S.A.,"1,059.38",12.59,2.29,"1,074.26",F003-0000174,"99,778.83","1,074.26","1,360.00",0.0,"1,418.38",KILOGRAMO BRUTO,0.75,"1,000.00",L,1.06,"kg, Kilogramo",0.0,DOL,STOLLER PERU SA,FOB,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01777779: JIMENEZ QUIROZ BORIS LENIN,ESSENCE,NaN,02777845-OCEAN NETWORK EXPRESS (ECUADOR) ONEEC...,PALOPEZ-LOPEZ POTES PAMELA ELIZABETH,0000-00-00,AFORO DOCUMENTAL,5190-VENTA AL POR MAYOR DE OTROS PRODUCTOS,JOSEGUANGO BAJO / PANAMERICANA NORTE S/N Y SEC...,NaN,AIR MAINLAND & SEA CARGO SERVICE S.A. AMSECARGO
9,RODELFLOWERS COMPANIA LIMITADA,NaN,NaN,1791353420001,RODEL FLOWERS CIA LTDS,3102.90.90.00,0,1,Los demás,"LOWER 7, FERTILIZANTES PARA FLORES",TRADECORP,SIN MODELO,2820241000008046,1,NaN,2024-01-02,2023-12-05,2023-12-30,2024-01-02,2024-01-03,2024-01-05,IMPORTACION A CONSUMO,NaN,CEC2023MSCU0490,CEC2023MSCU049000110000,MEDUVB151037,GUAYAQUIL MARITIMO,SPAIN,SPAIN,SPAIN,ESVLC-VALENCIA,MARITIMO,1.0,05906960-NAPORTEC S.A.,"15,116.00",0.00,151.16,"15,267.16",6483005528,"15,116.00","16,884.16","14,400.00",0.0,"15,335.00",KILOGRAMO BRUTO,0.99,"9,600.00",L,1.57,"kg, Kilogramo",0.0,DOL,TRADE CORPORATION INTERNATIONAL S.A,CIP,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,"15,116.00",0.00,151.16,"15,267.16","14,400.00",0.0,"16,884.16",0.0,0.00,0.0,NaN,NaN,01777855: SERRANO RODRIGUEZ MIGUEL ANGEL,MSC MIRELLA R,02908390-MEDITERRANEAN SHIPPING COMPANY DEL EC...,02908390-MEDITERRANEAN SHIPPING COMPANY DEL EC...,NaN,0000-00-00,AFORO AUTOMATICO,5121-VENTA AL POR MAYOR DE MATERIAS PRIMAS AGR...,FRANCISCO ROBLES E4 136 Y AMAZONAS,NaN,NaN
10,MORALVA CLTDA,NaN,NaN,992339640001,MORALVA C. LTDA.,3102.21.00.00,0,1,Sulfato de amonio,"SULFATO DE AMONIO GRANULAR, SULFATO DE AMONIO ...",SIN MARCA,SIN MODELO,2820241000009707,1,NaN,2024-01-03,2023-11-09,2023-12-30,2024-01-03,2024-01-03,2024-01-06,IMPORTACION A CONSUMO,NaN,CEC2023TBNA5015,CEC2023TBNA501500080000,5R7042XGG043,GUAYAQUIL MARITIMO,CHINA,CHINA,CHINA,CNXGG-XINGANG,MARITIMO,0.0,05909025-CONTECON GUAYAQUIL S.A.,"127,145.28",0.00,225.00,"127,370.28",TC23090230,"127,145.28","150,225.00","600,000.00",0.0,"600,000.00",KILOGRAMO BRUTO,0.21,"600,000.00",KG,0.21,"kg, Kilogramo",0.0,DOL,"TIANJIN CROWN CHAMPION INDUSTRIAL CO., LTD.",CFR,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,"127,145.28",0.00,225.00,"127,370.28","600,000.00",0.0,"150,225.00",0.0,0.00,0.0,NaN,NaN,01901316: ORGANIZACION COMERCIAL Y ADUANERA MA...,PACIFIC NEXUS,NaN,02908903-AGENCIA TECNICO MARITIMA TECNISEA C. ...,NaN,0000-00-00,AFORO AUTOMATICO,9993-OTROS,VIA A LA COSTA KM 6 1/2 LA VISTA SAN EDUARDO C...,NaN,NaN
11,SHELVES ECUADOR S.A.S.,NaN,NaN,1591726613001,SHELVES ECUADOR S.A.S.,3102.90.90.00,0,0,Los demás,"CALCIUM NITRATE TETRAHYDRATE, NITRATO DE CALCIO",SIN MARCA,SIN MODELO,2820241000010165,1,NaN,2024-01-03,2023-11-11,2023-12-31,2024-01-03,2024-01-04,2024-01-08,IMPORTACION A CONSUMO,NaN,CEC2023HLCU0914,CEC2023HLCU091461140000,MEDUUQ385368,GUAYAQUIL MARITIMO,CHINA,CHINA,CHINA,CNTXG-TIANJINXINGANG,MARITIMO,5.0,05907400-INARPI S.A.,"39,150.00",0.00,588.50,"39,738.50",SN20231013,"39,150.00","49,588.50","135,000.00",0.0,"135,540.00",KILOGRAMO BRUTO,0.29,135.00,TM,290.00,"kg, Kilogramo",0.0,DOL,"SHANDONG NOVAOIL TECHNOLOGY CO.,LTD",CIF,NaN,NUEVO,NaN,ECUADOR,"39,150.00",0.00,588.50,"39,738.50","135,000.00",0.0,"49,588.50",0.0,0.00,0.0,NaN,NaN,01777806: JATIVA LOPEZ WILMER HERNAN,VALOR,02908390-MEDITERRANEAN SHIPPING COMPANY DEL EC...,02908390-MEDITERRANEAN SHIPPING COMPANY DEL EC...,NaN,0000-00-00,AFORO AUTOMATICO,NaN,"AV. GENERAL RUMINAHUI AND AV. GENERAL PINTAG, ...",NaN,NaN
12,TRAVISER S.A.,NaN,NaN,992562560001,TRAVISER S.A.,3102.90.90.00,0,1,Los demás,"UREA PHOSPHATE, EN BOLSAS",SIN MARCA,SIN MODELO,2820241000010279,1,NaN,2024-01-03,2023-11-05,2023-12-29,2024-01-03,2024-01-03,2024-01-09,IMPORTACION A CONSUMO,NaN,CEC2023WHLU5692,CEC2023WHLU569200730000,033D515074,GUAYAQUIL MARITIMO,CHINA,CHINA,CHINA,CNTXG-TIANJINXINGANG,MARITIMO,2.0,05907400-INARPI S.A.,"60,786.40",0.00,224.69,"61,011.09",00008,"60,786.40","64,247.09","57,600.00",0.0,"57,600.00",KILOGRAMO BRUTO,1.06,57.60,TM,"1,055.32","kg, Kilogramo",0.0,DOL,P&T GROUP LLC,CPT,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,"60,786.40",0.00,224.69,"61,011.09","57,600.00",0.0,"64,247.09",0.0,0.00,0.0,NaN,NaN,01901316: ORGANIZACION COMERCIAL Y ADUANERA MA...,WAN HAI 621,07908255-AGENCIA MARITIMA GLOBAL MARGLOBAL SA,02901130-AGENCIA MARITIMA GLOBAL MARGLOBAL SA,RMACIAS-MACIAS ORELLANA RICHARD FRANCISCO,0000-00-00,AFORO FISICO INTRUSIVO,9993-OTROS,AV LEOPOLDO CARRERA EDIF OLIVOS BUSINESS CENTE...,NaN,NaN
13,YARECUADOR CIA LTDA,NaN,NaN,1792028140001,YARECUADOR CIA LTDA,3102.60.00.00,0,1,Sales dobles y mezclas entre si de nitrato de ...,"FERTILIZANTE, YARA TERA CALCINIT",YARA,30007630,2820241000013433,1,NaN,2024-01-03,2023-12-24,2024-01-01,2024-01-03,2024-01-03,2024-01-12,IMPORTACION A CONSUMO,NaN,CEC2024CMAU0001,CEC2024CMAU000190170000,HLCUBO2231207601,GUAYAQUIL MARITIMO,COLOMBIA,COLOMBIA,COLOMBIA,COCTG-CARTAGENA,MARITIMO,20.0,05777781-DPWORLD POSORJA S.A.,"191,700.09",0.00,"1,917.00","193,617.09",103153370,"191,700.09","206,131.59","540,000.00",0.0,"542,000.00",KILOGRAMO BRUTO,0.35,540.00,TM,355.00,"kg, Kilogramo",0.0,DOL,YARA COLOMBIA S.A.,CIP,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,"191,700.09",0.00,"1,917.00","193,617.09","540,000.00",0.0,"206,131.59",0.0,0.00,0.0,NaN,NaN,01902441: TORRES & TORRES AGENTES DE ADUANAS T...,CMA CGM ESTELLE,NaN,02777827-HAPAG-LLOYD ECUADOR S.A.,NaN,0000-00-00,AFORO AUTOMATICO,0140-ACTIVIDADES DE SERVICIOS AGRICOLAS Y GANA...,KM 1 5 SOLAR 120 Y LOS ARCOS EDIF LOS A,NaN,NaN
14,FERTILIZANTES DEL PACIFICO FERPACIFIC S.A.,NaN,NaN,991441336001,FERTILIZANTES DEL PACIFICO FERPACIFIC S.A.,3102.21.00.00,0,1,Sulfato de amonio,"AMMONIUM SULPHATE, FERTILIZANTE -1500 TONELADAS",SIN MARCA,FERTILIZANTE DE USO AGRICOLA,2820241000016221,1,NaN,2024-01-04,2023-11-09,2023-12-30,2024-01-04,2024-01-08,2024-01-12,IMPORTACION A CONSUMO,NaN,CEC2023TBNA5015,CEC2023TBNA501500030000,5R7042XGG039,GUAYAQUIL MARITIMO,CHINA,CHINA,CHINA,CNXGG-XINGANG,MARITIMO,0.0,05909025-CONTECON GUAYAQUIL S.A.,"225,000.00",0.00,399.00,"225,399.00",2023SHY-AS206,"225,000.00","285,399.00","1,500,000.00",0.0,"1,506,600.00",KILOGRAMO BRUTO,0.15,"1,500,000.00",KG,0.15,"kg, Kilogramo",0.0,DOL,ZHONGSHUO INTERNATIONAL TRADE CO. LTD,CFR,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,"225,000.00",0.00,399.00,"225,399.00","1,500,000.00",0.0,"285,399.00",0.0,0.00,0.0,NaN,NaN,01777837: VARYMPEX S.A.,PACIFIC NEXUS,NaN,02908903-AGENCIA TECNICO MARITIMA TECNISEA C. ...,ERIVERA-RIVERA HERNANDEZ ELENA LISBETH,0000-00-00,AFORO FISICO INTRUSIVO,0140-ACTIVIDADES DE SERVICIOS AGRICOLAS Y GANA...,"KM 16,5 VIA A DAULE",NaN,NaN
15,FERTILIZANTES DEL PACIFICO FERPACIFIC S.A.,NaN,NaN,991441336001,FERTILIZANTES DEL PACIFICO FERPACIFIC S.A.,3102.21.00.00,0,1,Sulfato de amonio,"AMMONIUM SULPHATE, FERTILIZANTE -500 TONELADAS",SIN MARCA,FERTILIZANTE DE USO AGRICOLA,2820241000016228,1,NaN,2024-01-04,2023-11-09,2023-12-30,2024-01-04,2024-01-08,2024-01-10,IMPORTACION A CONSUMO,NaN,CEC2023TBNA5015,CEC2023TBNA501500040000,5R7042XGG040,GUAYAQUIL MARITIMO,CHINA,CHINA,CHINA,CNXGG-XINGANG,MARITIMO,0.0,05909025-CONTECON GUAYAQUIL S.A.,"77,500.00",0.00,136.50,"77,636.50",2023MJ-AS207,"77,500.00","97,636.50","500,000.00",0.0,"501,200.00",KILOGRAMO BRUTO,0.15,"500,000.00",KG,0.16,"kg, Kilogramo",0.0,DOL,ZHONGSHUO INTERNATIONAL TRADE CO. LTD,CFR,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,"77,500.00",0.00,136.50,"77,636.50","500,000.00",0.0,"97,636.50",0.0,0.00,0.0,NaN,NaN,01777837: VARYMPEX S.A.,PACIFIC NEXUS,NaN,02908903-AGENCIA TECNICO MARITIMA TECNISEA C. ...,PALOPEZ-LOPEZ POTES PAMELA ELIZABETH,0000-00-00,AFORO DOCUMENTAL,0140-ACTIVIDADES DE SERVICIOS AGRICOLAS Y GANA...,"KM 16,5 VIA A DAULE",NaN,NaN
16,DUPOCSA PROTECTORES QUIMICOS PARA EL CAMPO S. A.,NaN,NaN,990856583001,DUPOCSA PROTECTORES QUIMICOS PARA EL CAMPO SA,3102.90.90.00,0,1,Los demás,"CRECIFOL, NINGUNA",MEZCLAS Y FERTILIZANTES S.A. DE C.V.,SIN MODELO,2820241000017692,1,NaN,2024-01-04,2023-12-16,2023-12-31,2024-01-04,2024-01-04,2024-01-05,IMPORTACION A CONSUMO,NaN,CEC2023HLCU0914,CEC2023HLCU091492480000,HLCUME3231150114,GUAYAQUIL MARITIMO,MEXICO,MEXICO,MEXICO,MXZLO-MANZANILLO,MARITIMO,1.0,05907400-INARPI S.A.,"2,892.74",0.00,4.93,"2,897.67",624,"14,678.39","3,238.93",720.72,0.0,749.72,KILOGRAMO BRUTO,3.86,462.00,L,6.26,"kg, Kilogramo",0.0,DOL,MEZCLAS Y FERTILIZANTES S.A. DE C.V.,CFR,0640-TRANSFERENCIAS E IMPORTACIONES CON TARIFA...,NUEVO,NaN,ECUADOR,"14,678.39",0.00,25.00,"14,703.40","6,492.72",0.0,"16,435.01",0.0,0.00,0.0,NaN,NaN,01777805: ROBLES MEDRANO ANDREA ESTEFANIA,VALOR,NaN,02777827-HAPAG-LLOYD ECUADOR S.A.,NaN,0000-00-00,AFORO AUTOMATICO,5190-VENTA AL POR MAYOR DE OTROS PRODUCTOS,"PARA EL CAMPO VIA DURAN - TAMBO KM 9, DURAN",NaN,NaN

Vamos a ver cuantas importaciones hay por posicion arancelaria

In [153]:
fertilizantes_2024['POSICION ARANCELARIA'].value_counts()

POSICION ARANCELARIA
3102.90.90.00    355
3102.21.00.00    195
3102.10.10.00    125
3102.60.00.00     85
3102.10.90.00     63
3102.30.00.00     57
3102.50.00.00     27
3102.29.00.00      9
3102.90.10.00      8
3102.80.00.00      3
Name: count, dtype: int64

Nos quedamos solo con las columnas que nos sirven

In [154]:
data_total_4 = ['POSICION ARANCELARIA', 'DESCRIPCION POSICION', 'FOB U$S', 'PAIS DESTINO', 'KGS NETO']
fertilizantes_2024 = fertilizantes_2024[data_total_4]

fertilizantes_2024

,POSICION ARANCELARIA,DESCRIPCION POSICION,FOB U$S,PAIS DESTINO,KGS NETO
0,3102.50.00.00,Nitrato de sodio,"154,400.00",ECUADOR,"200,000.00"
1,3102.10.90.00,Las demás,"264,671.41",ECUADOR,"239,880.00"
2,3102.10.90.00,Las demás,"181,204.70",ECUADOR,"308,233.00"
3,3102.60.00.00,Sales dobles y mezclas entre si de nitrato de ...,"27,000.00",ECUADOR,"100,000.00"
4,3102.10.90.00,Las demás,"183,255.36",ECUADOR,"311,488.00"
...,...,...,...,...,...
922,3102.60.00.00,Sales dobles y mezclas entre si de nitrato de ...,"43,578.44",ECUADOR,"200,000.00"
923,3102.21.00.00,Sulfato de amonio,"240,975.00",ECUADOR,"1,500,000.00"
924,3102.10.90.00,Las demás,"56,191.05",ECUADOR,"67,200.00"
925,3102.21.00.00,Sulfato de amonio,"76,117.50",ECUADOR,"497,500.00"
926,3102.60.00.00,Sales dobles y mezclas entre si de nitrato de ...,"15,470.00",ECUADOR,"65,000.00"

Cambio los nombres de las filas, por claridad

In [155]:
fertilizantes_2024 = fertilizantes_2024.rename(columns={
    'FOB U$S': 'Valor Total',
    'KGS NETO': 'Volumen Total en KGS'
})

Ahora contamos por posicion

In [156]:
fertilizantes_2024['DESCRIPCION POSICION'].value_counts()

DESCRIPCION POSICION
Los demás                                                                                                            355
Sulfato de amonio                                                                                                    195
Con un porcentaje de nitrógeno superior o igual a 45% pero inferior o igual a 46% en  peso (calidad fertilizante)    125
Sales dobles y mezclas entre si de nitrato de calcio y nitrato de amonio                                              85
Las demás                                                                                                             63
Nitrato de amonio, incluso en disolucion acuosa                                                                       57
Nitrato de sodio                                                                                                      27
Las demas                                                                                                              9
Mezclas de nitrato de calcio con nitrato de magnesio                                                                   8
Mezclas de urea con nitrato de amonio en disolución acuosa o amoniacal                                                 3
Name: count, dtype: int64

Cambiamos la fila de KGs y Valor Total a tipo float

In [157]:
columns_to_clean_2 = ['Valor Total', 'Volumen Total en KGS']

for column in columns_to_clean_2:
    fertilizantes_2024.loc[:, column] = (
        fertilizantes_2024[column]
        .astype(str)  
        .str.replace('$', '', regex=False)  
        .str.replace(',', '', regex=False)  
        .str.strip()  
    )

fertilizantes_2024[columns_to_clean_2] = fertilizantes_2024[columns_to_clean_2].apply(pd.to_numeric, errors='coerce')

In [158]:
fertilizantes_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 927 entries, 0 to 926
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   POSICION ARANCELARIA  927 non-null    object
 1   DESCRIPCION POSICION  927 non-null    object
 2   Valor Total           927 non-null    float64
 3   PAIS DESTINO          927 non-null    object
 4   Volumen Total en KGS  927 non-null    float64
dtypes: float64(2), object(3)
memory usage: 36.3+ KB

Veamos cuanto tengo en total, de volumen, por posicion arancelaria

In [159]:
fertilizantes_2024.groupby('POSICION ARANCELARIA')['Volumen Total en KGS'].sum().sort_values(ascending=False)

POSICION ARANCELARIA
3102.10.10.00    2.706688e+08
3102.21.00.00    1.575590e+08
3102.30.00.00    8.050914e+07
3102.90.90.00    3.722665e+07
3102.60.00.00    2.925940e+07
3102.10.90.00    5.790904e+06
3102.50.00.00    1.611881e+06
3102.29.00.00    2.043600e+05
3102.90.10.00    2.716842e+04
3102.80.00.00    8.672000e+03
Name: Volumen Total en KGS, dtype: float64

Me dan valores realistas, asi que bien.

Ahora compruebo NaNes y 0

In [160]:
fertilizantes_2024["Volumen Total en KGS"].isna().sum()

np.int64(0)

In [161]:
fertilizantes_2024["POSICION ARANCELARIA"].isna().sum()

np.int64(0)

Ahora que tengo las cantidades convertidas a numeros, voy a cambiar los nombres de las posiciones arancelarias, al nombre de su tipo de fertilizante.

In [163]:
mapeo_posiciones = {
    '3102.90.90.00': 'Nitrogenados',
    '3102.21.00.00': 'Sulfato de Amonio',
    '3102.10.10.00': 'Urea',
    '3102.60.00.00': 'Nitrogenados',
    '3102.10.90.00': 'Urea',
    '3102.30.00.00': 'Sulfato de Amonio',
    '3102.50.00.00': 'Urea',
    '3102.29.00.00': 'Urea',
    '3102.90.10.00': 'Urea',
    '3102.80.00.00': 'Nitrato de calcio'
}

# Nueva fila
fertilizantes_2024['Tipo de Fertilizante'] = fertilizantes_2024['POSICION ARANCELARIA'].map(mapeo_posiciones)

# Verifico el resultado
print("Muestra de la asignación de tipos de fertilizantes:")
print(fertilizantes_2024[['POSICION ARANCELARIA', 'Tipo de Fertilizante']].head(10))

# Sumo por tipo de fertilizante (agrupando los que son iguales)
volumen_por_tipo = fertilizantes_2024.groupby('Tipo de Fertilizante')['Volumen Total en KGS'].sum().sort_values(ascending=False)

# Convierto en Data Frame
volumen_tipo_df = volumen_por_tipo.reset_index()
volumen_tipo_df.columns = ['Tipo de Fertilizante', 'Volumen Total en KGS']

# Calculo el porcentaje
total_volumen = volumen_tipo_df['Volumen Total en KGS'].sum()
volumen_tipo_df['Porcentaje (%)'] = (volumen_tipo_df['Volumen Total en KGS'] / total_volumen * 100).round(2)

print(volumen_tipo_df)

Muestra de la asignación de tipos de fertilizantes:
  POSICION ARANCELARIA Tipo de Fertilizante
0        3102.50.00.00                 Urea
1        3102.10.90.00                 Urea
2        3102.10.90.00                 Urea
3        3102.60.00.00         Nitrogenados
4        3102.10.90.00                 Urea
5        3102.60.00.00         Nitrogenados
6        3102.21.00.00    Sulfato de Amonio
7        3102.90.90.00         Nitrogenados
8        3102.90.90.00         Nitrogenados
9        3102.90.90.00         Nitrogenados
  Tipo de Fertilizante  Volumen Total en KGS  Porcentaje (%)
0                 Urea          2.783031e+08           47.75
1    Sulfato de Amonio          2.380681e+08           40.84
2         Nitrogenados          6.648605e+07           11.41
3    Nitrato de calcio          8.672000e+03            0.00

Ahora guardamos estos resultados en un DataFrame

In [164]:
# Guardar el DataFrame con los resultados
resultado_mercado_fertilizantes_2024_porcentaje = volumen_tipo_df.copy()

In [165]:
resultado_mercado_fertilizantes_2024_porcentaje

  Tipo de Fertilizante  Volumen Total en KGS  Porcentaje (%)
0                 Urea          2.783031e+08           47.75
1    Sulfato de Amonio          2.380681e+08           40.84
2         Nitrogenados          6.648605e+07           11.41
3    Nitrato de calcio          8.672000e+03            0.00

In [166]:

resultado_mercado_fertilizantes_2024_porcentaje.to_csv('Data_2/resultado_mercado_fertilizantes_2024_porcentaje.csv', index=False)

Ahora vamos a importar un DataSet del clima en coordenadas de Guayaquil, desde el 2009 hasta 2024

In [169]:
clima_1 = pd.read_csv('https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2009/84117099999.csv')
clima_2 = pd.read_csv('https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2010/84117099999.csv')
clima_3 = pd.read_csv('https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2011/84117099999.csv')
clima_4 = pd.read_csv('https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2012/84117099999.csv')
clima_5 = pd.read_csv('https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2013/84117099999.csv')
clima_6 = pd.read_csv('https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2014/84117099999.csv')
clima_7 = pd.read_csv('https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2015/84117099999.csv')
clima_8 = pd.read_csv('https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2016/84117099999.csv')
clima_9 = pd.read_csv('https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2017/84117099999.csv')
clima_10 = pd.read_csv('https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2018/84117099999.csv')
clima_11 = pd.read_csv('https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2019/84117099999.csv')
clima_12 = pd.read_csv('https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2020/84117099999.csv')
clima_13 = pd.read_csv('https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2021/84117099999.csv')
clima_14 = pd.read_csv('https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2022/84117099999.csv')
clima_15 = pd.read_csv('https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2023/84117099999.csv')
clima_16 = pd.read_csv('https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2024/84117099999.csv')


pd.options.display.max_columns = None

clima_1
clima_16

,STATION,DATE,LATITUDE,LONGITUDE,ELEVATION,NAME,TEMP,TEMP_ATTRIBUTES,DEWP,DEWP_ATTRIBUTES,SLP,SLP_ATTRIBUTES,STP,STP_ATTRIBUTES,VISIB,VISIB_ATTRIBUTES,WDSP,WDSP_ATTRIBUTES,MXSPD,GUST,MAX,MAX_ATTRIBUTES,MIN,MIN_ATTRIBUTES,PRCP,PRCP_ATTRIBUTES,SNDP,FRSHTT
0,84117099999,2024-01-01,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",79.3,24,72.3,24,9999.9,0,999.9,0,6.2,23,6.8,23,13.0,999.9,84.2,*,75.2,*,0.00,I,999.9,0
1,84117099999,2024-01-02,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",79.2,21,72.1,21,9999.9,0,999.9,0,6.2,21,7.5,21,11.1,999.9,85.8,,75.2,*,0.00,I,999.9,0
2,84117099999,2024-01-03,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",80.0,23,71.8,23,1011.0,8,9.2,8,6.2,23,7.9,23,12.0,999.9,87.3,,75.6,,0.00,I,999.9,0
3,84117099999,2024-01-04,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",78.9,23,72.3,23,1011.6,5,9.8,5,6.2,23,5.8,23,13.0,999.9,84.9,,74.5,,0.00,B,999.9,0
4,84117099999,2024-01-05,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",79.1,22,72.5,22,1011.0,4,9.2,4,6.2,20,6.4,22,11.1,999.9,84.2,*,74.5,,0.00,I,999.9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,84117099999,2024-12-27,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",80.8,24,68.7,24,1010.3,4,8.5,4,6.2,24,9.1,24,14.0,999.9,90.1,,75.2,*,0.00,I,999.9,0
352,84117099999,2024-12-28,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",79.9,24,69.1,24,9999.9,0,999.9,0,6.2,24,6.1,24,12.0,999.9,89.2,,75.0,,0.00,I,999.9,0
353,84117099999,2024-12-29,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",77.2,23,71.6,23,9999.9,0,999.9,0,6.2,23,5.0,23,8.0,999.9,85.8,,73.4,*,0.08,G,999.9,10000
354,84117099999,2024-12-30,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",78.3,23,70.4,23,9999.9,0,999.9,0,6.2,23,5.8,23,8.9,999.9,84.2,*,74.7,,0.00,G,999.9,0
355,84117099999,2024-12-31,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",78.1,23,69.5,23,1010.8,4,9.0,4,6.2,23,7.3,23,13.0,999.9,84.9,,75.2,*,0.00,I,999.9,0

Ahora juntamos las tablas de todos los años en un unico dataset.

In [170]:
data_total_clima = pd.concat([clima_1, clima_2, clima_3, clima_4, clima_5, clima_6, clima_7, clima_8, clima_9, clima_10, clima_11, clima_12, clima_13, clima_14, clima_15, clima_16,], 
                       axis=0,           
                       ignore_index=True) 

data_total_clima

,STATION,DATE,LATITUDE,LONGITUDE,ELEVATION,NAME,TEMP,TEMP_ATTRIBUTES,DEWP,DEWP_ATTRIBUTES,SLP,SLP_ATTRIBUTES,STP,STP_ATTRIBUTES,VISIB,VISIB_ATTRIBUTES,WDSP,WDSP_ATTRIBUTES,MXSPD,GUST,MAX,MAX_ATTRIBUTES,MIN,MIN_ATTRIBUTES,PRCP,PRCP_ATTRIBUTES,SNDP,FRSHTT
0,84117099999,2009-01-01,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",76.1,24,67.3,24,9999.9,0,999.9,0,7.0,24,5.8,24,14.0,999.9,80.6,*,69.8,*,0.00,I,999.9,0
1,84117099999,2009-01-02,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",77.8,19,65.8,19,9999.9,0,999.9,0,7.0,19,7.9,19,14.0,999.9,82.4,*,75.2,*,0.00,I,999.9,0
2,84117099999,2009-01-03,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",78.7,22,67.0,22,9999.9,0,999.9,0,7.0,22,7.3,22,12.0,999.9,82.4,*,75.2,*,0.00,I,999.9,0
3,84117099999,2009-01-04,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",77.5,23,67.5,23,9999.9,0,999.9,0,6.9,23,5.2,23,8.9,999.9,84.2,*,73.4,*,99.99,,999.9,10000
4,84117099999,2009-01-05,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",79.3,22,67.7,22,9999.9,0,999.9,0,7.0,22,8.4,22,15.9,999.9,82.4,*,77.0,*,0.00,I,999.9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5800,84117099999,2024-12-27,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",80.8,24,68.7,24,1010.3,4,8.5,4,6.2,24,9.1,24,14.0,999.9,90.1,,75.2,*,0.00,I,999.9,0
5801,84117099999,2024-12-28,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",79.9,24,69.1,24,9999.9,0,999.9,0,6.2,24,6.1,24,12.0,999.9,89.2,,75.0,,0.00,I,999.9,0
5802,84117099999,2024-12-29,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",77.2,23,71.6,23,9999.9,0,999.9,0,6.2,23,5.0,23,8.0,999.9,85.8,,73.4,*,0.08,G,999.9,10000
5803,84117099999,2024-12-30,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",78.3,23,70.4,23,9999.9,0,999.9,0,6.2,23,5.8,23,8.9,999.9,84.2,*,74.7,,0.00,G,999.9,0
5804,84117099999,2024-12-31,-0.95,-80.683333,14.63,"ELOY ALFARO INTERNATIONAL, EC",78.1,23,69.5,23,1010.8,4,9.0,4,6.2,23,7.3,23,13.0,999.9,84.9,,75.2,*,0.00,I,999.9,0

Ahora voy a escoger solo las columnas que me convienen. Fecha, temperatura y precipitacion.

In [171]:
data_total_clima_2 = ['DATE', 'LATITUDE',
       'LONGITUDE', 'NAME', 'TEMP', 'PRCP']
data_total_clima = data_total_clima[data_total_clima_2]

data_total_clima

,DATE,LATITUDE,LONGITUDE,NAME,TEMP,PRCP
0,2009-01-01,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",76.1,0.00
1,2009-01-02,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",77.8,0.00
2,2009-01-03,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",78.7,0.00
3,2009-01-04,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",77.5,99.99
4,2009-01-05,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",79.3,0.00
...,...,...,...,...,...,...
5800,2024-12-27,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",80.8,0.00
5801,2024-12-28,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",79.9,0.00
5802,2024-12-29,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",77.2,0.08
5803,2024-12-30,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",78.3,0.00
5804,2024-12-31,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",78.1,0.00

Ahora voy a revisar cada columna.

In [ ]:
# Empezamos por DATE

In [172]:
len(data_total_clima[data_total_clima['DATE'] == '0000-00-00'])

0

In [173]:
data_total_clima['DATE'].value_counts()

DATE
2009-01-01    1
2019-08-31    1
2019-08-29    1
2019-08-28    1
2019-08-27    1
             ..
2014-04-28    1
2014-04-27    1
2014-04-26    1
2014-04-25    1
2024-12-31    1
Name: count, Length: 5805, dtype: int64

In [174]:
data_total_clima['DATE'].isna().sum()

np.int64(0)

Ahora revisamos LATITUDE

In [175]:
data_total_clima['LATITUDE'].value_counts()

LATITUDE
-0.95    5805
Name: count, dtype: int64

In [176]:
data_total_clima['LATITUDE'].isna().sum()

np.int64(0)

Ahora buscamos Ahora

In [177]:
data_total_clima['NAME'].value_counts()

NAME
ELOY ALFARO INTERNATIONAL, EC    5805
Name: count, dtype: int64

In [178]:
data_total_clima['NAME'].isna().sum()

np.int64(0)

Ahora revisamos TEMP

In [179]:
data_total_clima['TEMP'].value_counts()

TEMP
79.6    99
78.6    99
78.9    95
76.1    88
79.5    88
        ..
82.9     1
83.7     1
68.8     1
69.6     1
86.9     1
Name: count, Length: 139, dtype: int64

In [180]:
data_total_clima['TEMP'].isna().sum()

np.int64(0)

Ahora revisamos PRCP

In [181]:
data_total_clima['PRCP'].value_counts()

PRCP
0.00     5028
99.99     188
0.02       78
0.04       71
0.01       71
0.08       64
0.12       40
0.03       34
0.16       30
0.20       23
0.24       22
0.31       18
0.28       18
0.35       10
0.51        9
0.43        9
0.39        7
0.47        7
0.71        6
0.55        5
0.59        5
1.18        4
1.10        4
1.02        3
0.79        3
1.85        2
0.63        2
0.87        2
0.94        2
1.89        2
0.83        2
1.14        2
2.36        2
0.98        2
1.81        2
0.91        2
0.67        2
1.77        2
1.61        1
2.28        1
0.17        1
0.09        1
2.20        1
2.68        1
1.50        1
5.99        1
0.75        1
3.07        1
3.23        1
2.60        1
1.38        1
1.46        1
2.09        1
1.30        1
1.65        1
2.24        1
2.64        1
1.26        1
1.22        1
7.13        1
Name: count, dtype: int64

In [182]:
data_total_clima['PRCP'].isna().sum()

np.int64(0)

Ahora cambio la columna DATE por FECHA, para que cuadre con el dataframe anterior

In [183]:
data_total_clima = data_total_clima.rename(columns={'DATE': 'FECHA'})

In [184]:
data_total_clima

,FECHA,LATITUDE,LONGITUDE,NAME,TEMP,PRCP
0,2009-01-01,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",76.1,0.00
1,2009-01-02,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",77.8,0.00
2,2009-01-03,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",78.7,0.00
3,2009-01-04,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",77.5,99.99
4,2009-01-05,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",79.3,0.00
...,...,...,...,...,...,...
5800,2024-12-27,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",80.8,0.00
5801,2024-12-28,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",79.9,0.00
5802,2024-12-29,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",77.2,0.08
5803,2024-12-30,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",78.3,0.00
5804,2024-12-31,-0.95,-80.683333,"ELOY ALFARO INTERNATIONAL, EC",78.1,0.00

Cambio el formato de Fecha

In [185]:
data_total_clima['FECHA'] = pd.to_datetime(data_total_clima['FECHA'], format="%Y-%m-%d")

In [187]:
data_total_clima.to_csv('/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data_2/clima_si/data_total_clima.csv')

In [188]:
data_total_clima_filtrada = data_total_clima[["FECHA", "PRCP"]]

In [189]:
data_total_clima_filtrada

          FECHA   PRCP
0    2009-01-01   0.00
1    2009-01-02   0.00
2    2009-01-03   0.00
3    2009-01-04  99.99
4    2009-01-05   0.00
...         ...    ...
5800 2024-12-27   0.00
5801 2024-12-28   0.00
5802 2024-12-29   0.08
5803 2024-12-30   0.00
5804 2024-12-31   0.00

[5805 rows x 2 columns]

In [190]:
data_total_clima_filtrada["PRCP"].value_counts()

PRCP
0.00     5028
99.99     188
0.02       78
0.04       71
0.01       71
0.08       64
0.12       40
0.03       34
0.16       30
0.20       23
0.24       22
0.31       18
0.28       18
0.35       10
0.51        9
0.43        9
0.39        7
0.47        7
0.71        6
0.55        5
0.59        5
1.18        4
1.10        4
1.02        3
0.79        3
1.85        2
0.63        2
0.87        2
0.94        2
1.89        2
0.83        2
1.14        2
2.36        2
0.98        2
1.81        2
0.91        2
0.67        2
1.77        2
1.61        1
2.28        1
0.17        1
0.09        1
2.20        1
2.68        1
1.50        1
5.99        1
0.75        1
3.07        1
3.23        1
2.60        1
1.38        1
1.46        1
2.09        1
1.30        1
1.65        1
2.24        1
2.64        1
1.26        1
1.22        1
7.13        1
Name: count, dtype: int64

Ordenamos por fecha los valores donde la precipitacion es mayor a 0.00

In [ ]:
# Filtrar días con precipitación y ordenar por fecha. Tener en cuenta que una precipitacion se toma como apreciable si tiene un ratio mayor a 5
dias_con_lluvia = data_total_clima_filtrada[data_total_clima_filtrada['PRCP'] > 5.00]
dias_con_lluvia['FECHA'] = pd.to_datetime(dias_con_lluvia['FECHA'])
dias_lluvia = dias_con_lluvia.sort_values('FECHA')

dias_lluvia

/var/folders/9d/njcmv3bs67bgg_6p6s5pyjsw0000gn/T/ipykernel_3028/7602807.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dias_con_lluvia['FECHA'] = pd.to_datetime(dias_con_lluvia['FECHA'])

          FECHA   PRCP
3    2009-01-04  99.99
7    2009-01-08  99.99
9    2009-01-10  99.99
12   2009-01-13  99.99
13   2009-01-14  99.99
...         ...    ...
5467 2024-01-19  99.99
5485 2024-02-06  99.99
5552 2024-04-17  99.99
5599 2024-06-03   7.13
5786 2024-12-13  99.99

[190 rows x 2 columns]

Guardo los dias con mas precipitacion

In [192]:
dias_lluvia.to_csv('/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data_2/clima_si/dias_lluvia.csv')

Ahora sacamos promedio de precipitacion mes a mes

In [ ]:
data_total_clima_filtrada['Año'] = data_total_clima_filtrada['FECHA'].dt.year
data_total_clima_filtrada['Mes'] = data_total_clima_filtrada['FECHA'].dt.month

# Calculo por año y por mes
promedio_prcp_por_año_mes = data_total_clima_filtrada.groupby(['Año', 'Mes'])['PRCP'].mean().reset_index()
promedio_prcp_por_año_mes.columns = ['Año', 'Mes', 'Promedio PRCP']

# Y ordeno
promedio_prcp_por_año_mes = promedio_prcp_por_año_mes.sort_values(['Año', 'Mes'])

promedio_prcp_por_año_mes

/var/folders/9d/njcmv3bs67bgg_6p6s5pyjsw0000gn/T/ipykernel_3028/3928281582.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total_clima_filtrada['Año'] = data_total_clima_filtrada['FECHA'].dt.year
/var/folders/9d/njcmv3bs67bgg_6p6s5pyjsw0000gn/T/ipykernel_3028/3928281582.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_total_clima_filtrada['Mes'] = data_total_clima_filtrada['FECHA'].dt.month

      Año  Mes  Promedio PRCP
0    2009    1      25.808065
1    2009    2      10.744286
2    2009    3       0.029355
3    2009    4       6.666000
4    2009    5       9.676452
..    ...  ...            ...
187  2024    8       0.000000
188  2024    9       0.000000
189  2024   10       0.000000
190  2024   11       0.000000
191  2024   12       3.229677

[192 rows x 3 columns]

Guardo

In [195]:
promedio_prcp_por_año_mes.to_csv('/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data_2/clima_si/promedio_prcp_por_año_mes.csv')

Y por si es de utilidad guardo la data filtrada, que va dia a dia pero solo con precipitacion

In [196]:
data_total_clima_filtrada.to_csv('/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data_2/clima_si/data_total_clima_filtrada.csv')

<h1>Precios historicos</h1>

Empezamos por urea

In [197]:
data_1_precio_urea = pd.read_csv("/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data /Precios historicos UREA/Urea Granular FOB Middle East Futures Historical Data.csv")

In [198]:
data_1_precio_urea

            Date   Price    Open    High     Low   Vol. Change %
0     12/31/2024  369.00  369.00  369.00  369.00    NaN    0.00%
1     12/30/2024  369.00  369.00  369.00  369.00    NaN    0.00%
2     12/27/2024  369.00  369.00  369.00  369.00    NaN    0.82%
3     12/26/2024  366.00  366.00  366.00  366.00    NaN    0.00%
4     12/24/2024  366.00  366.00  366.00  366.00    NaN    0.00%
...          ...     ...     ...     ...     ...    ...      ...
1825  07/03/2017  186.50  186.50  186.50  186.50    NaN   -0.27%
1826  06/30/2017  187.00  187.00  187.00  187.00    NaN    0.40%
1827  06/29/2017  186.25  186.25  186.25  186.25  0.05K    0.13%
1828  06/28/2017  186.00  186.00  186.00  186.00    NaN   -0.13%
1829  06/27/2017  186.25  186.25  186.25  186.25    NaN   -0.53%

[1830 rows x 7 columns]

Primero renombro la columna Date a FECHA para que cuadre con los otros.

In [199]:
data_1_precio_urea = data_1_precio_urea.rename(columns={'Date': 'FECHA'})

In [252]:
data_1_precio_urea

           FECHA   Price    Open    High     Low   Vol. Change %
0     12/31/2024  369.00  369.00  369.00  369.00    NaN    0.00%
1     12/30/2024  369.00  369.00  369.00  369.00    NaN    0.00%
2     12/27/2024  369.00  369.00  369.00  369.00    NaN    0.82%
3     12/26/2024  366.00  366.00  366.00  366.00    NaN    0.00%
4     12/24/2024  366.00  366.00  366.00  366.00    NaN    0.00%
...          ...     ...     ...     ...     ...    ...      ...
1825  07/03/2017  186.50  186.50  186.50  186.50    NaN   -0.27%
1826  06/30/2017  187.00  187.00  187.00  187.00    NaN    0.40%
1827  06/29/2017  186.25  186.25  186.25  186.25  0.05K    0.13%
1828  06/28/2017  186.00  186.00  186.00  186.00    NaN   -0.13%
1829  06/27/2017  186.25  186.25  186.25  186.25    NaN   -0.53%

[1830 rows x 7 columns]

Ahora cambiamos la estructura de las fechas

In [200]:
data_1_precio_urea['FECHA'] = pd.to_datetime(data_1_precio_urea['FECHA']).dt.strftime('%Y-%m-%d')

Ahora removemos las columnas innutiles

In [201]:
data_1_precio_urea_filtrada = data_1_precio_urea.drop(columns=['Open', 'High', 'Low', 'Vol.'])

In [272]:
data_1_precio_urea_filtrada.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1830 entries, 0 to 1829
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   FECHA     1830 non-null   datetime64[ns]
 1   Price     1830 non-null   float64
 2   Change %  1830 non-null   object
 3   Año       1830 non-null   int32
 4   Mes       1830 non-null   int32
dtypes: datetime64[ns](1), float64(1), int32(2), object(1)
memory usage: 57.3+ KB

In [202]:
data_1_precio_urea_filtrada.to_csv('/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data_2/precios_historicos/data_1_precio_urea_filtrada.csv', index=False)

Ahora que tenemos el dia a dia de la Urea, vamos a sacar el precio y el % change por ano y mes

In [215]:
# # Convierto para que me pueda servir, aunque ya esta como date
data_1_precio_urea_filtrada['FECHA'] = pd.to_datetime(data_1_precio_urea_filtrada['FECHA'])

data_1_precio_urea_filtrada['Año'] = data_1_precio_urea_filtrada['FECHA'].dt.year
data_1_precio_urea_filtrada['Mes'] = data_1_precio_urea_filtrada['FECHA'].dt.month

# Cmabio change de object a numeric y remuevo cualquier %
if data_1_precio_urea_filtrada['Change %'].dtype == 'object':
    data_1_precio_urea_filtrada['Change %'] = data_1_precio_urea_filtrada['Change %'].str.replace('%', '')
    data_1_precio_urea_filtrada['Change %'] = data_1_precio_urea_filtrada['Change %'].str.replace(',', '.')
    data_1_precio_urea_filtrada['Change %'] = pd.to_numeric(data_1_precio_urea_filtrada['Change %'], errors='coerce')

# Calculo el mean de price y change por mes
promedio_precio_por_mes_urea = data_1_precio_urea_filtrada.groupby(['Año', 'Mes']).agg({
    'Price': 'mean',
    'Change %': 'mean'
}).reset_index()

promedio_precio_por_mes_urea.columns = ['Year', 'Month', 'Mean Price', 'Mean Change%']

promedio_precio_por_mes_urea['Mean Price'] = promedio_precio_por_mes_urea['Mean Price'].apply(lambda x: f"{x:.2f}")

promedio_precio_por_mes_urea['Mean Change%'] = promedio_precio_por_mes_urea['Mean Change%'].apply(lambda x: f"{x:.2f}%")

promedio_precio_por_mes_urea = promedio_precio_por_mes_urea.sort_values(['Year', 'Month'])

promedio_precio_por_mes_urea

    Year  Month Mean Price Mean Change%
0   2017      6     186.38       -0.03%
1   2017      7     186.30        0.28%
2   2017      8     209.76        0.37%
3   2017      9     243.25        1.07%
4   2017     10     279.27        0.48%
..   ...    ...        ...          ...
86  2024      8     339.00       -0.16%
87  2024      9     337.08        0.35%
88  2024     10     369.99        0.18%
89  2024     11     354.02       -0.35%
90  2024     12     353.18        0.35%

[91 rows x 4 columns]

Guardo el promedio de urea por mes

In [216]:
promedio_precio_por_mes_urea.to_csv('/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data_2/precios_historicos/promedio_precio_por_mes_urea.csv', index=False)

Ahora voy a transferir los datos del precio del ETF de Gas Natural

In [207]:
data_1_precio_nat_gas = pd.read_csv("/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data /Precios Historicos Nat Gas/FCG ETF Stock Price History.csv")

In [208]:
data_1_precio_nat_gas

            Date  Price   Open   High    Low     Vol. Change %
0     03/28/2025  24.64  24.70  24.80  24.43  140.47K   -0.61%
1     03/27/2025  24.79  24.96  25.05  24.66  197.88K   -1.78%
2     03/26/2025  25.24  25.37  25.62  25.18  133.59K    0.24%
3     03/25/2025  25.18  25.20  25.38  25.07  326.65K    0.16%
4     03/24/2025  25.14  24.83  25.23  24.83  183.09K    1.66%
...          ...    ...    ...    ...    ...      ...      ...
4110  01/08/2009  66.10  65.10  66.10  63.96    8.01K    0.99%
4111  01/07/2009  65.45  68.60  68.65  64.42    7.67K   -4.24%
4112  01/06/2009  68.35  67.50  69.70  67.50    8.56K    3.09%
4113  01/05/2009  66.30  63.60  67.15  63.60   16.09K    5.66%
4114  01/02/2009  62.75  59.40  63.33  59.40    8.29K    6.54%

[4115 rows x 7 columns]

Empezamos cambiando la columna de Date  Fecha

In [209]:
data_1_precio_nat_gas = data_1_precio_nat_gas.rename(columns={'Date': 'FECHA'})

Ahora cambiaremos la estructura de las fechas

In [210]:
data_1_precio_nat_gas['FECHA'] = pd.to_datetime(data_1_precio_nat_gas['FECHA']).dt.strftime('%Y-%m-%d')

Removemos las columnas innutiles

In [211]:
data_1_precio_nat_gas_filtrado = data_1_precio_nat_gas.drop(columns=['Open', 'High', 'Low', 'Vol.'])

Guardamos esta data de todos los dias

In [212]:
data_1_precio_nat_gas_filtrado.to_csv('/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data_2/precios_historicos/data_1_precio_nat_gas_filtrado.csv', index=False)

In [217]:
# Seguimos el mismo proceso anterior
data_1_precio_nat_gas_filtrado['FECHA'] = pd.to_datetime(data_1_precio_nat_gas_filtrado['FECHA'])

data_1_precio_nat_gas_filtrado['Año'] = data_1_precio_nat_gas_filtrado['FECHA'].dt.year
data_1_precio_nat_gas_filtrado['Mes'] = data_1_precio_nat_gas_filtrado['FECHA'].dt.month

if data_1_precio_nat_gas_filtrado['Change %'].dtype == 'object':
    data_1_precio_nat_gas_filtrado['Change %'] = data_1_precio_nat_gas_filtrado['Change %'].str.replace('%', '')
    data_1_precio_nat_gas_filtrado['Change %'] = data_1_precio_nat_gas_filtrado['Change %'].str.replace(',', '.')
    data_1_precio_nat_gas_filtrado['Change %'] = pd.to_numeric(data_1_precio_nat_gas_filtrado['Change %'], errors='coerce')

promedio_precio_por_mes_gas = data_1_precio_nat_gas_filtrado.groupby(['Año', 'Mes']).agg({
    'Price': 'mean',
    'Change %': 'mean'
}).reset_index()

promedio_precio_por_mes_gas.columns = ['Año', 'Mes', 'Mean Precio', 'Mean Cambio%']

promedio_precio_por_mes_gas['Mean Precio'] = promedio_precio_por_mes_gas['Mean Precio'].apply(lambda x: f"{x:.2f}")

promedio_precio_por_mes_gas['Mean Cambio%'] = promedio_precio_por_mes_gas['Mean Cambio%'].apply(lambda x: f"{x:.2f}%")

promedio_precio_por_mes_gas = promedio_precio_por_mes_gas.sort_values(['Año', 'Mes'])

promedio_precio_por_mes_gas

      Año  Mes Mean Precio Mean Cambio%
0    2009    1       60.78        0.07%
1    2009    2       56.80       -0.80%
2    2009    3       48.68        0.11%
3    2009    4       56.98        0.97%
4    2009    5       67.55        1.02%
..    ...  ...         ...          ...
190  2024   11       25.30        0.53%
191  2024   12       24.35       -0.27%
192  2025    1       25.98        0.06%
193  2025    2       25.06       -0.10%
194  2025    3       23.95        0.08%

[195 rows x 4 columns]

In [218]:
promedio_precio_por_mes_gas.to_csv('/Users/auric/REPO_TEST/Entregas/Entrega 28 - 03 de abril de marzo/EDA Agricultura_Clima Ecuador/EDA/Data_2/precios_historicos/promedio_precio_por_mes_gas.csv', index=False)